# (PART) CoreStats 3: Continuous predictors {.unnumbered}

# Introduction {#cs3-intro}

## Objectives
:::objectives
**Aim: To introduce R commands for analysing simple linear models**

By the end of this practical participants should be able to perform the following statistical analyses:

1.	Simple Linear Regression
2.	Correlation

For each of these, participants should be able to:

a.	Perform the test in R
b.	Interpret the output
c.	Check the assumptions of the test
:::

## Background

This practical focuses on the implementation of various statistical tests relating to simple linear regression and correlation.

Again, it does not focus on the underlying theory of the tests (although the demonstrators will be happy to answer any questions that you may have).

For each test there will be a section that:

* explains the purpose of the test,
* explains how to visualise the data,
* explains how to perform the test in R,
* explains how to interpret the output and report the results, and 
* explains how to assess the assumptions required to perform the test.
