# (PART) CoreStats 6: Power analysis {.unnumbered}

# Introduction {#cs6-intro}

## Objectives
:::objectives
**To introduce R commands for conducting power analyses and for practising systematic statistical analysis**

By the end of this practical participants should be able to:

1. apply _a priori_ power analysis techniques for t-tests and linear models in order to determine appropriate sample sizes for a given effect size, power and significance levels
2. systematically analyse and produce readable statistical reports on previously unseen simple datasets containing a single continuous, binary or proportion response variable and multiple categorical or continuous predictor variables
:::

## Background
This practical consists of two separate sections:

The first looks at power analysis of t-tests and linear models.

The second section consists of a single worked example plus a series of example datasets, all of which can be analysed and written up using R techniques explored in the previous practicals. It can be considered an opportunity to review all of the techniques that we’ve looked at during this course. Details of the R commands are not given here and instead it is expected that you will use the previous materials if you need to look up the various commands. This is intentional and aims to reflect how you would use the course resources in the future!
