# essential libraries
library(knitr)
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(car))
#suppressPackageStartupMessages(library(dunn.test))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(rstatix))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(ggfortify))
suppressPackageStartupMessages(library(ggResidpanel))
library(pwr)
library(powerAnalysis)
theme_set(theme_bw())
