# essential libraries
library(downlit)
library(corrr)
library(reticulate)
library(knitr)
library(tidyverse)
library(kableExtra)
library(car)
library(dunn.test)
library(broom)
library(rstatix)
library(patchwork)
#library(ggfortify)
library(ggResidpanel)
library(pwr)
#library(powerAnalysis)
theme_set(theme_bw())
