{
  "hash": "fe27b7c54014c2241685205dbc5c3d68",
  "result": {
    "markdown": "---\ntitle: \"Mann-Whitney U test\"\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n::: callout-tip\n## Learning outcomes\n\n**Questions**\n\n- When do I perform a two-sample test on non-normal data?\n- What are the assumptions?\n- How do I interpret and present the results of the test?\n\n**Objectives**\n\n- Set out your hypothesis for comparing two samples of non-normal continuous data\n- Be able to summarise and visualise the data\n- Understand and assess the underlying assumptions of the test\n- Perform a Mann-Whitney U test\n- Be able to interpret and report the results\n\n:::\n\nThis test also compares two samples, however for this test (in contrast to Student's t-test) we don't have to assume that the parent distributions are normally distributed. In order to compare the medians of the two groups we do still need the parent distributions (and consequently the samples) to both have the same shape and variance. In this test we look to see if the medians of the two parent distributions differ significantly from each other.\n\n## Libraries and functions\n\n::: {.callout-note collapse=\"true\"}\n## Click to expand\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\n### Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# A collection of R packages designed for data science\nlibrary(tidyverse)\n```\n:::\n\n\n### Functions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Performs one- and two-sample Wilcoxon tests\n# on vectors of data; the latter is also known\n# as 'Mann-Whitney' test\nstats::wilcox.test()\n```\n:::\n\n\n## R\n\n### Functions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Performs one- and two-sample Wilcoxon tests\n# on vectors of data; the latter is also known\n# as 'Mann-Whitney' test\nstats::wilcox.test()\n```\n:::\n\n\n## Python\n\n| Libraries  | Description                                                              |\n|:-------------------|:---------------------------------------------------|\n| `pandas`   | A Python data analysis and manipulation tool.                            |\n| `pingouin` | A Python module developed to have simple yet exhaustive stats functions. |\n\n| Functions                                                                               | Description                                                         |\n|:-----------------------------------|:-----------------------------------|\n| `pandas.DataFrame.pivot()`                                                              | Return reshaped DataFrame organised by given index / column values. |\n| [`pingouin.mwu()`](https://pingouin-stats.org/generated/pingouin.mwu.html#pingouin.mwu) | Performs the Mann-Whitney U test.                                   |\n:::\n:::\n\n## Data and hypotheses\n\nAgain, we use the `rivers` data set. We want to test whether the median body length of male guppies differs between samples. We form the following null and alternative hypotheses:\n\n-   $H_0$: The difference in median body length between the two groups is 0 $(\\mu A - \\mu G = 0)$\n-   $H_1$: The difference in median body length between the two groups is not 0 $(\\mu A - \\mu G \\neq 0)$\n\nWe use a two-tailed Mann-Whitney U test to see if we can reject the null hypothesis.\n\n## Summarise and visualise\n\nWe did this in the [previous section](#cs1-students-sumvisual).\n\n## Assumptions\n\nWe have checked these previously.\n\n## Implement and interpret the test\n\nCalculate the median for each group (for reference) and perform a two-tailed, Mann-Whitney U test:\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\nCalculate the median:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrivers %>% \n    group_by(river) %>% \n    summarise(median_length = median(length))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  river   median_length\n  <chr>           <dbl>\n1 Aripo            20.1\n2 Guanapo          18.8\n```\n:::\n:::\n\n\nPerform the Mann-Whitney U test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(length ~ river,\n            alternative = \"two.sided\",\n            data = rivers)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  length by river\nW = 841, p-value = 0.0006464\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n-   The first argument must be in the formula format: `variable ~ category`\n-   The second argument gives the type of alternative hypothesis and must be one of `two.sided`, `greater` or `less`\n\nYou *may* get a warning message in the console stating `cannot compute exact p-value with ties`. This just means that some of the data points have exactly the same value which affects the internal mathematics slightly. However, given that the p-value is so very small, this is not something that we need to worry about.\n\nAfter the warning message:\n\n-   The 1st line gives the name of the test and the 2nd line reminds you what the dataset was called, and what variables were used\n-   The 3rd line contains the two key outputs from the test:\n    -   The calculated W-value is 841 (we'll use this in reporting)\n    -   The p-value is 0.0006464.\n-   The 4th line simply states the alternative hypothesis in terms of the difference between the two sample medians in that if there were a difference then one distribution would be shifted relative to the other.\n\n## R\nCalculate the median:\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(length ~ river,\n          FUN = median,\n          data = rivers_r)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    river length\n1   Aripo   20.1\n2 Guanapo   18.8\n```\n:::\n:::\n\n\nThe `aggregate()` function uses the same formula notation as we've used previously. It also takes a `FUN =` argument, which is the function it applies to each subgroup. In this case we're calculating the `median` `length` for each `river`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(length ~ river, data = rivers_r,\n            alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot\ncompute exact p-value with ties\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  length by river\nW = 841, p-value = 0.0006464\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\nYou may get a warning message in the console stating `cannot compute exact p-value with ties`. This just means that some of the data points have exactly the same value which affects the internal mathematics slightly. However, given that the p-value is so very small, this is not something that we need to worry about.\n\nAfter the warning message:\n\n-   The 1st line gives the name of the test and the 2nd line reminds you what the dataset was called, and what variables were used\n-   The 3rd line contains the two key outputs from the test:\n    -   The calculated W-value is 841\n    -   The p-value is 0.0006464.\n-   The 4th line simply states the alternative hypothesis in terms of the difference between the two sample medians in that if there were a difference then one distribution would be shifted relative to the other.\n\n## Python\n\nBefore we can implement the Mann-Whitney U test, we need to reformat our data a bit.\n\nThe `pg.mwu()` function requires the numerical input for the two groups it needs to compare.\n\nThe easiest way is to reformat our data from the *long* format where all the data are stacked on top of one another to the *wide* format, where the `length` values are in separate columns for the two rivers.\n\nWe can do this with the `pd.pivot()` function. We save the output in a new object and then access the values as required. It keeps all the data separate, meaning that there will be missing values `NaN` in this format. The `pg.mwu()` function ignores missing values by default.\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# reformat the data into a 'wide' format\nrivers_py_wide = pd.pivot(rivers_py,\n                          columns = 'river',\n                          values = 'length')\n      \n# have a look at the format\nrivers_py_wide.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nriver  Aripo  Guanapo\n0        NaN     19.1\n1        NaN     23.3\n2        NaN     18.2\n3        NaN     16.4\n4        NaN     19.7\n```\n:::\n:::\n\n\nNext, we can calculate the median values for each river:\n\n\n::: {.cell}\n\n```{.python .cell-code}\nrivers_py_wide['Aripo'].median()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n20.1\n```\n:::\n\n```{.python .cell-code}\nrivers_py_wide['Guanapo'].median()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n18.8\n```\n:::\n:::\n\n\nFinally, we can perform the Mann-Whitney U test:\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# perform the Mann-Whitney U test\n# ignoring the missing values\npg.mwu(rivers_py_wide['Aripo'],\n       rivers_py_wide['Guanapo'])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     U-val alternative     p-val       RBC     CLES\nMWU  841.0   two-sided  0.000646 -0.487179  0.74359\n```\n:::\n:::\n\n:::\n\nGiven that the p-value is less than 0.05 we can reject the null hypothesis at this confidence level. Again, the p-value on the 3rd line is what we're most interested in. Since the p-value is very small (much smaller than the standard significance level) we choose to say \"that it is very unlikely that these two samples came from the same parent distribution and as such we can reject our null hypothesis\".\n\nTo put it more completely, we can state that:\n\n> A Mann-Whitney test indicated that the median body length of male guppies in the Guanapo river ($\\tilde{x}$ = 18.8 mm) differs significantly from the median body length of male guppies in the Aripo river ($\\tilde{x}$ = 20.1 mm, p = 0.0006).\n\n## Exercise: Turtles (revisited)\n\nAnalyse the turtle data set from before using a Mann-Whitney U test.\n\nWe follow the same process as with Student's t-test.\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n\n### Hypotheses\n\n$H_0$ : male median $=$ female median\n\n$H_1$ : male median $\\neq$ female median\n\n### Summarise and visualise\n\nThis is the same as before.\n\n### Assumptions\n\nWe've already checked that the variances of the two groups are similar, so we're OK there. Whilst the Mann-Whitney U test doesn't require normality or symmetry of distributions it does require that the distributions have the same shape. In this example, with just a handful of data points in each group, it's quite hard to make this call one way or another. My advice in this case would be say that unless it's obvious that the distributions are very different we can just allow this assumption to pass, and you're only going see obvious differences in distribution shape when you have considerably more data points than we have here.\n\n### Carry out a Mann-Whitney test\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(serum ~ sex,\n            alternative = \"two.sided\",\n            data = turtle)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  serum by sex\nW = 26, p-value = 0.5338\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(serum ~ sex,\n            alternative = \"two.sided\",\n            data = turtle_r)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  serum by sex\nW = 26, p-value = 0.5338\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\n# reformat the data into a 'wide' format\nturtle_py_wide = pd.pivot(turtle_py,\n                          columns = 'sex',\n                          values = 'serum')\n      \n# have a look at the format\nturtle_py_wide.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsex  Female   Male\n0       NaN  220.1\n1       NaN  218.6\n2       NaN  229.6\n3       NaN  228.8\n4       NaN  222.0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.python .cell-code}\n# perform the Mann-Whitney U test\n# ignoring the missing values\npg.mwu(turtle_py_wide['Male'],\n       turtle_py_wide['Female'])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     U-val alternative   p-val       RBC      CLES\nMWU   16.0   two-sided  0.5338  0.238095  0.380952\n```\n:::\n:::\n\n:::\n\nThis gives us exactly the same conclusion that we got from the two-sample t-test _i.e_. that there isn't any significant difference between the two groups.\n\n> A Mann-Whitney test indicated that there wasn't a significant difference in the median serum cholesterol levels between male and female turtles (p = 0.534)\n:::\n",
    "supporting": [
      "cs1_practical_two-sample-mann-whitney_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}