{
  "hash": "04846e1661eba38feecde5ca086de4ec",
  "result": {
    "markdown": "---\ntitle: \"Multiple linear regression\"\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n::: callout-tip\n## Learning outcomes\n\n**Questions**\n\n- How do I use the linear model framework with three predictor variables?\n\n**Objectives**\n\n- Be able to expand the linear model framework with three predictor variables\n- Define the equation for the line of best fit for each categorical variable\n- Be able to construct and analyse any possible combination of predictor variables in the data\n:::\n\n## Libraries and functions\n\n::: {.callout-note collapse=\"true\"}\n## Click to expand\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\n### Libraries\n### Functions\n\n## R\n\n### Libraries\n### Functions\n\n## Python\n\n### Libraries\n### Functions\n:::\n:::\n\n## Purpose and aim\nRevisiting the linear model framework and expanding to systems with three predictor variables.\n\n## Data and hypotheses\n\nThe data set we'll be using is located in `data/CS5-pm2_5.csv`. It contains data on air pollution levels measured in London, in 2019. It also contains several meteorological measurements. Each variable was recorded on a daily basis.\n\nNote: some of the variables are based on simulations.\n\nIt contains the following variables:\n\n| variable | explanation |\n|:--|:--|\n| `avg_temp`| average daily temperature ($^\\circ C$)|\n| `date`| date of record|\n| `location`| location in London (`inner` or `outer`) |\n| `pm2_5`| concentration of PM2.5 ($\\mu g / m^3$)|\n| `rain_mm`| daily rainfall in mm (same across both locations)|\n| `wind_m_s`| wind speed in $m/s$|\n\n## Summarise and visualise\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\nLet's first load the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npm2_5 <- read_csv(\"data/CS5-pm2_5.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 730 Columns: 6\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (2): date, location\ndbl (4): avg_temp, pm2_5, rain_mm, wind_m_s\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nhead(pm2_5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 6\n  avg_temp date       location pm2_5 rain_mm wind_m_s\n     <dbl> <chr>      <chr>    <dbl>   <dbl>    <dbl>\n1      4.5 01/01/2019 inner     17.1     2.3     3.87\n2      4.9 01/01/2019 outer     10.8     2.3     5.84\n3      4.3 02/01/2019 inner     14.9     2.3     3.76\n4      4.8 02/01/2019 outer     11.4     2.3     6   \n5      4   03/01/2019 inner     18.5     1.4     2.13\n6      4.5 03/01/2019 outer     15.0     1.4     2.57\n```\n:::\n:::\n\n\nIt's the `pm2_5` response variable we're interested in here. Let's start by checking if there might be a difference between PM2.5 level in inner and outer London:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pm2_5, aes(x = location, y = pm2_5)) +\n    geom_boxplot() +\n    geom_jitter(width = 0.1, alpha = 0.7)\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nI've added the (jittered) data to the plot, with some transparency (`alpha = 0.7`). It's always good to look at the actual data and not just summary statistics (which is what the box plot is).\n\nThere seems to be quite a difference between the PM2.5 levels in the two London areas, with the levels in inner London being markedly higher. I'm not surprised by this! So when we do our statistical testing, I would expect to find a clear difference between the locations.\n\nApart from the location, there are quite a few numerical descriptor variables. We could plot them one-by-one, but that's a bit tedious. So instead we use the `pairs()` function again. This only works on numerical data, so we select all the columns that are numeric with `select_if(is.numeric)`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npm2_5 %>% \n    select_if(is.numeric) %>% \n    pairs(lower.panel = NULL)\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nWe can see that there is not much of a correlation between `pm2_5` and `avg_temp` or `rain_mm`, whereas there might be something going on in relation to `wind_m_s`.\n\nOther notable things include that rainfall seems completely independent of wind speed (rain fall seems pretty constant). Nor does the average temperature seem in any way related to wind speed (it looks like a random collection of data points!).\n\nWe can visualise the relationship between `pm2_5` and `wind_m_s` in a bit more detail, by plotting the data against each other and colouring by `location`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pm2_5, aes(x = wind_m_s, y = pm2_5,\n                  colour = location)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis seems to show that there might be some linear relationship between PM2.5 levels and wind speed.\n\nAnother way of looking at this would be to create a correlation matrix, like we did before in the [correlations chapter](cs3_practical_correlations.qmd#correlation-coefficients):\n\n\n::: {.cell}\n\n```{.r .cell-code}\npm2_5 %>% \n    select_if(is.numeric) %>% \n    cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            avg_temp       pm2_5     rain_mm    wind_m_s\navg_temp  1.00000000  0.03349457  0.03149221 -0.01107855\npm2_5     0.03349457  1.00000000 -0.02184951 -0.41733945\nrain_mm   0.03149221 -0.02184951  1.00000000  0.04882097\nwind_m_s -0.01107855 -0.41733945  0.04882097  1.00000000\n```\n:::\n:::\n\n\nThis confirms what we saw in the plots, there aren't any very strong correlations between the different (numerical) variables, apart from a negative correlation between `pm2_5` and `wind_m_s`, which has a Pearson's r of $r$ = -0.42.\n\n## R\n\nLet's first load the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npm2_5_r <- read.csv(\"data/CS5-pm2_5.csv\")\n\nhead(pm2_5_r)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  avg_temp       date location  pm2_5 rain_mm wind_m_s\n1      4.5 01/01/2019    inner 17.126     2.3     3.87\n2      4.9 01/01/2019    outer 10.821     2.3     5.84\n3      4.3 02/01/2019    inner 14.884     2.3     3.76\n4      4.8 02/01/2019    outer 11.416     2.3     6.00\n5      4.0 03/01/2019    inner 18.471     1.4     2.13\n6      4.5 03/01/2019    outer 15.008     1.4     2.57\n```\n:::\n:::\n\n\nIt's the `pm2_5` response variable we're interested in here. Let's start by checking if there might be a difference between PM2.5 level in inner and outer London:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(pm2_5 ~ location, col = \"white\", data = pm2_5_r)\n\nstripchart(pm2_5 ~ location,\n           data = pm2_5_r,\n           method = \"jitter\",\n           pch = 19,\n           col = alpha(\"black\", 0.4),\n           vertical = TRUE,\n           add = TRUE)\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nI've added the (jittered) data to the plot. To do this I've used the `stripchart()` function and added some transparency (`col = alpha(\"black\", 0.4)`). It's always good to look at the actual data and not just summary statistics (which is what the box plot is).\n\nThere seems to be quite a difference between the PM2.5 levels in the two London areas, with the levels in inner London being markedly higher. I'm not surprised by this! So when we do our statistical testing, I would expect to find a clear difference between the locations.\n\nApart from the location, there are quite a few numerical descriptor variables. We could plot them one-by-one, but that's a bit tedious. So instead we use the `pairs()` function again. This only works on numerical data, so we select all the columns that are numeric with the base R `Filter()` function (not to be confused with the `dplyr::filter()` function). Note that there are many different ways to select numeric-only columns and a quick Google search will lead you to [Stackoverflow](https://stackoverflow.com/questions/5863097/selecting-only-numeric-columns-from-a-data-frame).\n\nWe could save the output of the `Filter()` operation into a new variable and use that with the `pairs()` function. However, since version 4.1 R has had a native pipe, using the `|>` symbol. There are some  [differences](https://towardsdatascience.com/understanding-the-native-r-pipe-98dea6d8b61b) between tidyverse's `%>%` and base R's `|>`, but we won't delve into this here.\n\nSuffice to say, we can do the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFilter(is.numeric, pm2_5_r) |> pairs(lower.panel = NULL)\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nWe can see that there is not much of a correlation between `pm2_5` and `avg_temp` or `rain_mm`, whereas there might be something going on in relation to `wind_m_s`.\n\nOther notable things include that rainfall seems completely independent of wind speed (rain fall seems pretty constant). Nor does the average temperature seem in any way related to wind speed (it looks like a random collection of data points!).\n\nWe can visualise the relationship between `pm2_5` and `wind_m_s` in a bit more detail, by plotting the data against each other and colouring by `location`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(pm2_5 ~ wind_m_s,\n     col = factor(location),\n     data = pm2_5_r)\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThis seems to show that there might be some linear relationship between PM2.5 levels and wind speed.\n\nAnother way of looking at this would be to create a correlation matrix, like we did before in the [correlations chapter](materials/cs3_practical_correlations.qmd#correlation-coefficients). Again, this only works on numerical values, so we get all the numerical columns and send this to the `cor()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFilter(is.numeric, pm2_5_r) |> cor()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            avg_temp       pm2_5     rain_mm    wind_m_s\navg_temp  1.00000000  0.03349457  0.03149221 -0.01107855\npm2_5     0.03349457  1.00000000 -0.02184951 -0.41733945\nrain_mm   0.03149221 -0.02184951  1.00000000  0.04882097\nwind_m_s -0.01107855 -0.41733945  0.04882097  1.00000000\n```\n:::\n:::\n\n\nThis confirms what we saw in the plots, there aren't any very strong correlations between the different (numerical) variables, apart from a negative correlation between `pm2_5` and `wind_m_s`, which has a Pearson's r of $r$ = -0.42.\n\n## Python\n\nLet's first load the data:\n\n\n::: {.cell}\n\n```{.python .cell-code}\npm2_5_py = pd.read_csv(\"data/CS5-pm2_5.csv\")\n\npm2_5_py.head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   avg_temp        date location   pm2_5  rain_mm  wind_m_s\n0       4.5  01/01/2019    inner  17.126      2.3      3.87\n1       4.9  01/01/2019    outer  10.821      2.3      5.84\n2       4.3  02/01/2019    inner  14.884      2.3      3.76\n3       4.8  02/01/2019    outer  11.416      2.3      6.00\n4       4.0  03/01/2019    inner  18.471      1.4      2.13\n```\n:::\n:::\n\n\nIt's the `pm2_5` response variable we're interested in here. Let's start by checking if there might be a difference between PM2.5 level in inner and outer London:\n\n\n::: {.cell}\n\n```{.python .cell-code}\n(ggplot(pm2_5_py, aes(x = \"location\", y = \"pm2_5\")) +\n    geom_boxplot() +\n    geom_jitter(width = 0.1, alpha = 0.7))\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-14-1.png){width=614}\n:::\n:::\n\n\nI've added the (jittered) data to the plot, with some transparency (`alpha = 0.7`). It's always good to look at the actual data and not just summary statistics (which is what the box plot is).\n\nThere seems to be quite a difference between the PM2.5 levels in the two London areas, with the levels in inner London being markedly higher. I'm not surprised by this! So when we do our statistical testing, I would expect to find a clear difference between the locations.\n\nApart from the location, there are quite a few numerical descriptor variables. At this point I should probably bite the bullet and install `seaborn`, so I can use the [pairplot()](https://seaborn.pydata.org/generated/seaborn.pairplot.html) function.\n\nBut I'm not going to ;-)\n\nI'll just tell you that there is not much of a correlation between `pm2_5` and `avg_temp` or `rain_mm`, whereas there might be something going on in relation to `wind_m_s`. So I plot that instead and colour it by location:\n\n\n::: {.cell}\n\n```{.python .cell-code}\n(ggplot(pm2_5_py, aes(x = \"wind_m_s\",\n                      y = \"pm2_5\",\n                      colour = \"location\")) +\n     geom_point())\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-15-3.png){width=614}\n:::\n:::\n\n\nThis seems to show that there might be some linear relationship between PM2.5 levels and wind speed.\n\nIf I would plot all the other variables against each other, then I would spot that rainfall seems completely independent of wind speed (rain fall seems pretty constant). Nor does the average temperature seem in any way related to wind speed (it looks like a random collection of data points!). You can check this yourself!\n\nAnother way of looking at this would be to create a correlation matrix, like we did before in the [correlations chapter](materials/cs3_practical_correlations.qmd#correlation-coefficients):\n\n\n::: {.cell}\n\n```{.python .cell-code}\npm2_5_py.corr()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          avg_temp     pm2_5   rain_mm  wind_m_s\navg_temp  1.000000  0.033495  0.031492 -0.011079\npm2_5     0.033495  1.000000 -0.021850 -0.417339\nrain_mm   0.031492 -0.021850  1.000000  0.048821\nwind_m_s -0.011079 -0.417339  0.048821  1.000000\n```\n:::\n:::\n\n\nThis confirms what we saw in the plots, there aren't any very strong correlations between the different (numerical) variables, apart from a negative correlation between `pm2_5` and `wind_m_s`, which has a Pearson's r of $r$ = -0.42.\n:::\n\n## Implement and interpret the test\n\nFrom our initial observations we derived that there might be some relationship between PM2.5 levels and wind speed. We also noticed that this is likely to be different between inner and outer London.\n\nIf we would want to test for _every_ variable and interaction, then we would end up with a rather huge model, which would even include 3-way and a 4-way interaction! To illustrate the point that the process of model testing applies to as many variables as you like, we're adding the `avg_temp` and `rain_mm` variables to our model.\n\nSo in this case we create a model that takes into account all of the main effects (`avg_temp`, `location`, `rain_mm`, `wind_m_s`). We also include a potential two-way interaction (`location:wind_m_s`). The two-way interaction may be of interest since the PM2.5 levels in response to wind speed seem to differ between the two locations.\n\nOur model is then as follows:\n\n`pm2_5 ~ avg_temp, location + rain_mm + wind_m_s + wind_m_s:location`\n\nSo let's define and explore it!\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\nWe write the model as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_full <- lm(pm2_5 ~ avg_temp + location + rain_mm + wind_m_s +\n                       wind_m_s:location, data = pm2_5)\n```\n:::\n\n\nThis will give us quite a few coefficients, so instead of just calling the `lm` object, I'm restructuring the output using the `tidy()` function from the `broom` package. It's installed with `tidyverse` but you have to load it separately using `library(broom)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_full %>%\n    tidy() %>% \n    select(term, estimate, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 3\n  term                   estimate  p.value\n  <chr>                     <dbl>    <dbl>\n1 (Intercept)             18.2    0       \n2 avg_temp                 0.0105 1.90e- 1\n3 locationouter           -2.07   1.44e-25\n4 rain_mm                 -0.0279 5.63e- 1\n5 wind_m_s                -0.285  6.36e-25\n6 locationouter:wind_m_s  -0.429  1.57e-27\n```\n:::\n:::\n\n\nFrom this we can see that the interaction between `location` and `wind_m_s` is statistically significant. Which means that we can't just talk about the effect of `location` or `wind_m_s` on PM2.5 levels, without taking the other variable into account!\n\nThe p-values for the `avg_temp` and `rain_mm` main effects are not significant. This means that they're not contributing much to model's ability to explain our data. This matches what we already saw when we visualised the data.\n\nWhat to do? We'll explore this in more detail in the chapter on model comparisons, but for now the most sensible option would be to redefine the model, but exclude those two variables. Here I have rewritten the model, using the shorthand `*` notation (`pm2_5 ~ location * wind_m_s` is equal to `pm2_5 ~ location + wind_m_s + wind_m_s:location`). I've named it `lm_pm2_5_red` to indicate it is a reduced model (with fewer variables than our original full model):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_red <- lm(pm2_5 ~ location * wind_m_s, data = pm2_5)\n```\n:::\n\n\nLet's look at the new model coefficients:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_red %>%\n    tidy() %>% \n    select(term, estimate, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 3\n  term                   estimate  p.value\n  <chr>                     <dbl>    <dbl>\n1 (Intercept)              18.2   0       \n2 locationouter            -2.06  2.02e-25\n3 wind_m_s                 -0.285 5.74e-25\n4 locationouter:wind_m_s   -0.432 6.50e-28\n```\n:::\n:::\n\n\nAs we did in the linear regression on grouped data, we end up with two linear equations, one for `inner` London and one for `outer` London.\n\nOur reference group is `inner` (remember, it takes a reference group in alphabetical order and we can see `outer` in the output).\n\nSo we end up with:\n\n$PM2.5_{inner} = 18.24 - 0.29 \\times wind\\_m\\_s$\n\n$PM2.5_{outer} = (18.24 - 2.06) + (-0.29 - 0.43) \\times wind\\_m\\_s$\n\nwhich gives\n\n$PM2.5_{outer} = 16.18 - 0.72 \\times wind\\_m\\_s$\n\n\nWe still need to check the assumptions of the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_red %>% \n    resid_panel(plots = c(\"resid\", \"qq\", \"ls\", \"cookd\"),\n              smoother = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nThey all look pretty good, with the only weird thing being a small empty zone of predicted values just under 16. Nothing that is getting me worried though.\n\nIt'd be useful to visualise the model. We can take the model and use the `augment()` function to extract the fitted values (`.fitted`). These are the values for `pm2_5` that the model is predicting. We can then plot these against the `wind_m_s` measurements, colouring by `location`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_red %>% \n    augment() %>% \n    ggplot(aes(x = wind_m_s, y = .fitted, colour = location)) +\n    geom_line(size = 1) +\n    # add the original data\n    geom_point(data = pm2_5, aes(wind_m_s, pm2_5, colour = location))\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nNote: in this case we're actually visualising the model with both the main effects and the interaction between them. This is also the default behaviour for the `lm` method of `geom_smooth()`, so we could have also plotted it with:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = pm2_5, aes(x = wind_m_s, y = pm2_5,\n                         colour = location)) +\n    geom_smooth(method = \"lm\", se = FALSE)\n```\n:::\n\n\n## R\n## Python\n:::\n\n## Exploring models\n\nRather than stop here however, we will use the concept of the linear model to its full potential and show that we can construct and analyse any possible combination of predictor variables for this data set. Namely we will consider the following four extra models, where reduce the complexity to the model, step-by-step:\n\n| Model| Description|\n|:- |:- |\n|1. `pm2_5 ~ wind_m_s + location`| An additive model |\n|2. `pm2_5 ~ wind_m_s` | Equivalent to a simple linear regression |\n|3. `pm2_5 ~ location` | Equivalent to a one-way ANOVA |\n|4. `pm2_5 ~ 1` | The null model, where we have no predictors |\n\n### Additive model\n\nTo create the additive model, we drop the interaction term (keep in mind, this is to demonstrate the process - we would normally not do this because the interaction term is significant!).\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\nFirst, we define the model:\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_add <- lm(pm2_5 ~ location + wind_m_s,\n                   data = pm2_5)\n```\n:::\n\n\nWe can visualise this as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_add %>% \n    augment() %>% \n    ggplot(aes(x = wind_m_s, y = .fitted,\n               colour = location)) +\n    geom_line(size = 1) +\n    geom_point(data = pm2_5,\n               aes(x = wind_m_s, y = pm2_5))\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nNext, we extract the coefficient estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_add %>%\n    tidy() %>% \n    select(term, estimate, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  term          estimate   p.value\n  <chr>            <dbl>     <dbl>\n1 (Intercept)     19.2   0        \n2 locationouter   -4.05  1.11e-233\n3 wind_m_s        -0.499 3.98e- 96\n```\n:::\n:::\n\n\n## R\n## Python\n:::\n\nSo our two equations would be as follows:\n\n$PM2.5_{inner} = 19.22 - 0.50 \\times wind\\_m\\_s$\n\n$PM2.5_{outer} = (19.22 - 4.05) - 0.50 \\times wind\\_m\\_s$\n\ngives\n\n$PM2.5_{outer} = 15.17 - 0.50 \\times wind\\_m\\_s$\n\n### Revisiting linear regression\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\nFirst, we define the model:\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_wind <- lm(pm2_5 ~ wind_m_s,\n                   data = pm2_5)\n```\n:::\n\n\nWe can visualise this as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_wind %>% \n    augment() %>% \n    ggplot(aes(x = wind_m_s, y = .fitted)) +\n    geom_line(colour = \"blue\", size = 1) +\n    geom_point(data = pm2_5,\n               aes(x = wind_m_s, y = pm2_5))\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Alternative using `geom_smooth()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pm2_5, aes(x = wind_m_s, y = pm2_5)) +\n    geom_point() +\n    geom_smooth(method = \"lm\", se = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n:::\n\nNext, we extract the coefficient estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_wind %>%\n    tidy() %>% \n    select(term, estimate, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term        estimate  p.value\n  <chr>          <dbl>    <dbl>\n1 (Intercept)   17.3   0       \n2 wind_m_s      -0.529 3.94e-32\n```\n:::\n:::\n\n\n## R\n## Python\n:::\n\nThis gives us the following equation:\n\n$PM2.5 = 17.33 - 0.53 \\times wind\\_m\\_s$\n\n### Revisiting ANOVA\n\nIf we're just looking at the effect of `location`, then we're essentially doing a one-way ANOVA.\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\nFirst, we define the model:\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_loc <- lm(pm2_5 ~ location,\n                   data = pm2_5)\n```\n:::\n\n\nWe can visualise this as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_loc %>% \n    augment() %>% \n    ggplot(aes(x = location, y = .fitted)) +\n    geom_point(colour = \"blue\", size = 3) +\n    geom_jitter(data = pm2_5,\n                aes(x = location, y = pm2_5),\n                width = 0.1,\n                alpha = 0.2)\n```\n\n::: {.cell-output-display}\n![](cs5_practical_multiple-linear-regression_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nOK, what's going on here? I've plotted the `.fitted` values (the values predicted by the model) in blue and overlaid the original (with a little bit of jitter to avoid overplotting). However, there are only two predicted values!\n\nWe can check this and see that each unique fitted value occurs 365 times:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_loc %>% \n    augment() %>% \n    count(location, .fitted)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  location .fitted     n\n  <chr>      <dbl> <int>\n1 inner       16.9   365\n2 outer       12.8   365\n```\n:::\n:::\n\n\nThis makes sense if we think back to our original ANOVA exploration. There we established that an ANOVA is just a special case of a linear model, where the fitted values are equal to the mean of each group.\n\nWe could even check this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npm2_5 %>% \n    group_by(location) %>% \n    summarise(mean_pm2_5 = mean(pm2_5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  location mean_pm2_5\n  <chr>         <dbl>\n1 inner          16.9\n2 outer          12.8\n```\n:::\n:::\n\n\nSo, that matches. We move on and extract the coefficient estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_loc %>%\n    tidy() %>% \n    select(term, estimate, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 3\n  term          estimate   p.value\n  <chr>            <dbl>     <dbl>\n1 (Intercept)      16.9  0        \n2 locationouter    -4.11 4.82e-170\n```\n:::\n:::\n\n\nThese values match up exactly with the predicted values for each individual location.\n\n## R\n## Python\n:::\n\nThis gives us the following equation:\n\n$\\bar{PM2.5_{inner}} = 16.94$\n\n$\\bar{PM2.5_{outer}} = 16.94 - 4.11 = 12.83$\n\n### The null model\n\nThe null model by itself is rarely analysed for its own sake but is instead used a reference point for more sophisticated model selection techniques. It represents your data as an overal average value.\n\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n\nWe define the null model as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_null <- lm(pm2_5 ~ 1,\n                    data = pm2_5)\n```\n:::\n\nWe can just view the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_pm2_5_null\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = pm2_5 ~ 1, data = pm2_5)\n\nCoefficients:\n(Intercept)  \n      14.89  \n```\n:::\n:::\n\n\n\n## R\n## Python\n:::\n\nThis shows us that there is just one value: 14.8871411. This is the average across all the PM2.5 values in the data set.\n\nHere we'd predict the PM2.5 values as follows:\n\n$PM2.5 = 14.89$ \n\n## Exercise\n\n::: {.callout-tip collapse=\"true\"}\n## Answer\n::: {.panel-tabset group=\"language\"}\n## tidyverse\n## R\n## Python\n:::\n:::\n\n## Key points\n\n::: callout-note\n-\n-\n-\n:::\n",
    "supporting": [
      "cs5_practical_multiple-linear-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}