<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="no-js">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Chapter 12 ANOVA | Core Statistics in R</title>
<meta name="author" content="Matt Castle and Martin van Rongen">
<meta name="description" content="12.1 Objectives  Questions How do I analyse multiple samples of continuous data? What is an ANOVA? How do I check for differences between groups? Objectives Be able to perform an ANOVA in R...">
<meta name="generator" content="bookdown 0.25 with bs4_book()">
<meta property="og:title" content="Chapter 12 ANOVA | Core Statistics in R">
<meta property="og:type" content="book">
<meta property="og:description" content="12.1 Objectives  Questions How do I analyse multiple samples of continuous data? What is an ANOVA? How do I check for differences between groups? Objectives Be able to perform an ANOVA in R...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 12 ANOVA | Core Statistics in R">
<meta name="twitter:description" content="12.1 Objectives  Questions How do I analyse multiple samples of continuous data? What is an ANOVA? How do I check for differences between groups? Objectives Be able to perform an ANOVA in R...">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references --><link rel="shortcut icon" href="favicon.ico">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<!-- CSS : implied media="all" --><link rel="stylesheet" href="stylesheets/full-stylesheet.css">
<link rel="stylesheet" href="stylesheets/styleguide.css">
<link rel="stylesheet" href="stylesheets/style.css">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><script type="text/javascript" src="//use.typekit.com/hyb5bko.js"></script><script type="text/javascript">try{Typekit.load();}catch(e){}</script><script type="text/javascript">  document.documentElement.className += " js";</script>
</head>
<body class="campl-theme-2" data-spy="scroll" data-target="#toc">

<!--[if lt IE 7]>
<div class="lt-ie9 lt-ie8 lt-ie7">
<![endif]-->
<!--[if IE 7]>
<div class="lt-ie9 lt-ie8">
<![endif]-->
<!--[if IE 8]>
<div class="lt-ie9">
<![endif]-->

	<a href="#primary-nav" class="campl-skipTo">skip to primary navigation</a>
	<a href="#content" class="campl-skipTo">skip to content</a>
	<div class="campl-row campl-global-header">
		<div class="campl-wrap clearfix">
			<div class="campl-header-container campl-column8" id="global-header-controls">
				<a href="http://www.cam.ac.uk" class="campl-main-logo">
					<img alt="University of Cambridge" src="images/interface/main-logo-small.png" height="38px;"></a>

				<ul class="campl-unstyled-list campl-horizontal-navigation campl-global-navigation clearfix">
<li>
						<a href="#study-with-us">Study at Cambridge</a>
					</li>
					<li>
						<a href="#about-the-university">About the University</a>
					</li>
					<li>
						<a href="http://www.cam.ac.uk/research" class="campl-no-drawer">Research at Cambridge</a>
					</li>
				</ul>
</div>

			<div class="campl-column2">
				<div class="campl-quicklinks">
				</div>
			</div>

			<div class="campl-column2">

				<div class="campl-site-search" id="site-search-btn">

					<label for="header-search" class="hidden">Search site</label>
					<div class="campl-search-input">
						<form action="http://search.cam.ac.uk/web" method="get">
						<input id="header-search" type="text" name="query" value="" placeholder="Search"><input type="image" class="campl-search-submit " src="images/interface/btn-search-header.png">
</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="campl-row campl-global-header campl-search-drawer">
		<div class="campl-wrap clearfix">
			<form class="campl-site-search-form" id="site-search-container" action="">
				<div class="campl-search-form-wrapper clearfix">
					<input type="text" class="text" placeholder="Search"><input type="image" class="campl-search-submit" src="images/interface/btn-search.png">
</div>
			</form>
		</div>
	</div>

	<div class="campl-row campl-global-navigation-drawer">

		<div class="campl-wrap clearfix">
			<div class="campl-column12 campl-home-link-container">
				<a href="">Home</a>
			</div>
		</div>
		<div class="campl-wrap clearfix">
			<div class="campl-column12 campl-global-navigation-mobile-list campl-global-navigation-list">
				<div class="campl-global-navigation-outer clearfix" id="study-with-us">
					<ul class="campl-unstyled-list campl-global-navigation-header-container ">
<li><a href="http://www.cam.ac.uk/study-at-cambridge">Study at Cambridge</a></li>
					</ul>
<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list campl-global-navigation-secondary-with-children">
<li>
								<a href="http://www.study.cam.ac.uk/undergraduate/">Undergraduate</a>
								<ul class="campl-global-navigation-tertiary campl-unstyled-list">
<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/courses">Courses</a>
									</li>
									<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/applying">Applying</a>
									</li>
									<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/events">Events and open days</a>
									</li>
								  <li>
										<a href="http://www.undergraduate.study.cam.ac.uk/finance">Fees and finance</a>
									</li>
								  <li>
										<a href="http://www.becambridge.com/">Student blogs and videos</a>
									</li>
								</ul>
</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list campl-global-navigation-secondary-with-children">
<li>
								<a href="http://www.graduate.study.cam.ac.uk/">Graduate</a>
								<ul class="campl-global-navigation-tertiary campl-unstyled-list">
<li>
										<a href="http://www.graduate.study.cam.ac.uk/why-cambridge/welcome-vice-chancellor">Why Cambridge</a>
									</li>
									<li>
										<a href="http://www.graduate.study.cam.ac.uk/courses%0A">Course directory</a>
									</li>
									<li>
									<a href="http://www.graduate.study.cam.ac.uk/how-do-i-apply">How to apply</a>
</li>
									<li><a href="http://www.cambridgestudents.cam.ac.uk/fees-and-funding">Fees and funding</a></li>
									<li><a href="http://www.graduate.study.cam.ac.uk/faqs/applicant">Frequently asked questions</a></li>
								</ul>
</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list last">
<li>
								<a href="http://www.internationalstudents.cam.ac.uk">International students</a>
							</li>
							<li>
								<a href="http://www.ice.cam.ac.uk">Continuing education</a>
							</li>
							<li>
								<a href="http://www.epe.admin.cam.ac.uk/">Executive and professional education</a>
							</li>
							<li>
								<a href="http://www.educ.cam.ac.uk">Courses in education</a>
							</li>
						</ul>
</div>
				</div>

				<div class="campl-global-navigation-outer clearfix" id="about-the-university">
					<ul class="campl-global-navigation-header-container campl-unstyled-list">
<li><a href="http://www.cam.ac.uk/about-the-university">About the University</a></li>
					</ul>
<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.cam.ac.uk/about-the-university/how-the-university-and-colleges-work">How the University and Colleges work</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/history">History</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/visiting-the-university">Visiting the University</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/term-dates-and-calendars">Term dates and calendars</a>
							</li>
							<li class="last">
								<a href="http://map.cam.ac.uk">Map</a>
							</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.communications.cam.ac.uk/">For media</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/video-and-audio">Video and audio</a>
							</li>
							<li>
								<a href="http://webservices.admin.cam.ac.uk/fae/">Find an expert</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/publications">Publications</a>
							</li>
							<li class="last">
								<a href="http://www.cam.ac.uk/global-cambridge">Global Cambridge</a>
							</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.cam.ac.uk/news">News</a>
							</li>
							<li>
								<a href="http://www.admin.cam.ac.uk/whatson/">Events</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/public-engagement">Public engagement</a>
							</li>
							<li>
								<a href="http://www.jobs.cam.ac.uk">Jobs</a>
							</li>
							<li class="last">
								<a href="https://www.philanthropy.cam.ac.uk/">Give to Cambridge</a>
							</li>
						</ul>
</div>
				</div>

				<div class="campl-global-navigation-outer clearfix" id="our-research">
					<ul class="campl-global-navigation-header-container campl-unstyled-list">
<li><a href="">Research at Cambridge</a></li>
					</ul>
</div>
			</div>

			<ul class="campl-unstyled-list campl-quicklinks-list campl-global-navigation-container ">
<li>
					<a href="http://www.cam.ac.uk/for-staff">For staff</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/current-students">For current students</a>
				</li>
				<li>
					<a href="http://www.alumni.cam.ac.uk">For alumni</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/for-business">For business</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/colleges-and-departments">Colleges &amp; departments</a>
				</li>
				<li>
					<a href="http://www.lib.cam.ac.uk/libraries/">Libraries &amp; facilities</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/museums-and-collections">Museums &amp; collections</a>
				</li>
				<li class="last">
					<a href="http://www.cam.ac.uk/email-and-phone-search">Email &amp; phone search</a>
				</li>
			</ul>
</div>
	</div>
    <!-- .campl-global-header ends -->

	<div class="campl-row campl-page-header campl-sub-section-page">
		<div class="campl-wrap clearfix">
			<div class="campl-column12">
				<div class="campl-content-container">
					<div class="campl-breadcrumb" id="breadcrumb">
						<ul class="campl-unstyled-list campl-horizontal-navigation clearfix">
<li class="first-child">
								<a href="https://bioinfotraining.bio.cam.ac.uk/" class="campl-home ir">Home</a>
							</li>
							<li>
								<a href="">Courses</a>
							</li>
							<li>
								<a href="">Training Materials</a>
							</li>
							<li>
								<a href="index.html">Core Statistics in R
							</a>
</li>
						</ul>
</div>
					<!--<p class="campl-page-title">Bioinformatics Training Materials</p>-->

					<p class="campl-mobile-parent"><a href=""><span class="campl-back-btn campl-menu-indicator"></span>Studying at Cambridge</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="campl-row campl-page-header">
		<div class="campl-wrap clearfix campl-local-navigation" id="local-nav">
			<div class="campl-local-navigation-container">
				<ul class="campl-unstyled-list">
<li><a href="https://training.cam.ac.uk/bioinformatics/search">Course schedule</a></li>
					<li>
<a href="#" class="campl-selected">Additional information</a>
						<ul class="campl-unstyled-list local-dropdown-menu">
<li><a href="#">Additional resources</a></li>
							<li><a href="https://bioinfotraining.bio.cam.ac.uk/about/findus">Where to find us?</a></li>
							<li><a href="#">Frequently asked questions</a></li>
						</ul>
</li>
					<li><a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate">Further training</a></li>
				</ul>
</div>
		</div>



		<div class="campl-wrap clearfix campl-page-sub-title campl-recessed-sub-title">
			<div class="campl-column12">
				<div class="campl-content-container">
					<p class="campl-sub-title">Core Statistics in R</p>
				</div>
			</div>
		</div>
	</div>


		<div class="campl-row campl-content campl-recessed-content">
			<div class="campl-wrap clearfix">
				<div class="campl-column9  campl-main-content" id="content">
					<div class="campl-content-container">
						<div>
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <br><button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Overview</a></li>
<li class="book-part">CoreStats 1: Simple hypothesis testing</li>
<li><a class="" href="cs1-intro.html"><span class="header-section-number">2</span> Introduction</a></li>
<li class="book-part">CoreStats 1 (Practicals)</li>
<li><a class="" href="introduction.html"><span class="header-section-number">3</span> Introduction</a></li>
<li><a class="" href="cs1-one-sample-t-test.html"><span class="header-section-number">4</span> One-sample t-test</a></li>
<li><a class="" href="cs1-onesample-wilcoxon-signed-rank.html"><span class="header-section-number">5</span> Wilcoxon signed-rank test</a></li>
<li><a class="" href="cs1-students-t-test.html"><span class="header-section-number">6</span> Student’s t-test</a></li>
<li><a class="" href="cs1-mannwhitney-u-test.html"><span class="header-section-number">7</span> Mann-Whitney U test</a></li>
<li><a class="" href="cs1-paired-two-sample-t-test.html"><span class="header-section-number">8</span> Paired two-sample t-test</a></li>
<li><a class="" href="cs1-twosample-wilcoxon-signed-rank.html"><span class="header-section-number">9</span> Wilcoxon signed-rank test</a></li>
<li class="book-part">CoreStats 2: Categorical predictors</li>
<li><a class="" href="cs2-intro.html"><span class="header-section-number">10</span> Introduction</a></li>
<li class="book-part">CoreStats 2 (Practicals)</li>
<li><a class="" href="introduction-1.html"><span class="header-section-number">11</span> Introduction</a></li>
<li><a class="active" href="cs2-anova.html"><span class="header-section-number">12</span> ANOVA</a></li>
<li><a class="" href="kruskal-wallis-test.html"><span class="header-section-number">13</span> Kruskal-Wallis test</a></li>
<li class="book-part">CoreStats 3: Continuous predictors</li>
<li><a class="" href="cs3-intro.html"><span class="header-section-number">14</span> Introduction</a></li>
<li class="book-part">CoreStats 3 (Practicals)</li>
<li><a class="" href="introduction-2.html"><span class="header-section-number">15</span> Introduction</a></li>
<li><a class="" href="correlation-coefficients.html"><span class="header-section-number">16</span> Correlation coefficients</a></li>
<li><a class="" href="linear-regression.html"><span class="header-section-number">17</span> Linear regression</a></li>
<li class="book-part">CoreStats 4: Two predictor variables</li>
<li><a class="" href="cs4-intro.html"><span class="header-section-number">18</span> Introduction</a></li>
<li class="book-part">CoreStats 4 (Practicals)</li>
<li><a class="" href="introduction-3.html"><span class="header-section-number">19</span> Introduction</a></li>
<li><a class="" href="two-way-anova.html"><span class="header-section-number">20</span> Two-way ANOVA</a></li>
<li><a class="" href="linear-regression-with-grouped-data.html"><span class="header-section-number">21</span> Linear regression with grouped data</a></li>
<li class="book-part">CoreStats 5: Multiple predictor variables</li>
<li><a class="" href="cs5-intro.html"><span class="header-section-number">22</span> Introduction</a></li>
<li class="book-part">CoreStats 5 (Practicals)</li>
<li><a class="" href="introduction-4.html"><span class="header-section-number">23</span> Introduction</a></li>
<li><a class="" href="linear-models.html"><span class="header-section-number">24</span> Linear models</a></li>
<li><a class="" href="model-comparisons.html"><span class="header-section-number">25</span> Model comparisons</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="cs2-anova" class="section level1" number="12">
<h1>
<span class="header-section-number">12</span> ANOVA<a class="anchor" aria-label="anchor" href="#cs2-anova"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-2" class="section level2" number="12.1">
<h2>
<span class="header-section-number">12.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-2"><i class="fas fa-link"></i></a>
</h2>
<div class="objectives">
<p><strong>Questions</strong></p>
<ul>
<li>How do I analyse multiple samples of continuous data?</li>
<li>What is an ANOVA?</li>
<li>How do I check for differences between groups?</li>
</ul>
<p><strong>Objectives</strong></p>
<ul>
<li>Be able to perform an ANOVA in R</li>
<li>Understand the ANOVA output and evaluate the assumptions</li>
<li>Understand what post-hoc testing is and how to do this in R</li>
</ul>
</div>
</div>
<div id="purpose-and-aim-2" class="section level2" number="12.2">
<h2>
<span class="header-section-number">12.2</span> Purpose and aim<a class="anchor" aria-label="anchor" href="#purpose-and-aim-2"><i class="fas fa-link"></i></a>
</h2>
<p>Analysis of variance or ANOVA is a test than can be used when we have multiple samples of continuous data. Whilst it is possible to use ANOVA with only two samples, it is generally used when we have three or more groups. It is used to find out if the samples came from parent distributions with the same mean. It can be thought of as a generalisation of the two-sample Student’s t-test.</p>
</div>
<div id="section-commands-6" class="section level2" number="12.3">
<h2>
<span class="header-section-number">12.3</span> Section commands<a class="anchor" aria-label="anchor" href="#section-commands-6"><i class="fas fa-link"></i></a>
</h2>
<p>New commands used in this section.</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Function</th>
<th align="left">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code></td>
<td align="left">Fits a linear model</td>
</tr>
<tr class="even">
<td align="left"><code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code></td>
<td align="left">Carries out an ANOVA on a linear model</td>
</tr>
<tr class="odd">
<td align="left"><code><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel()</a></code></td>
<td align="left">Creates diagnostic plots</td>
</tr>
</tbody>
</table></div>
<p>We also use functionality from a new library, <code>ggResidPanel</code>:</p>
<div class="sourceCode" id="cb90"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># load ggResidPanel, for ggplot-friendly diagnostics plots</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://goodekat.github.io/ggResidpanel/">ggResidpanel</a></span><span class="op">)</span></code></pre></div>
</div>
<div id="data-and-hypotheses-5" class="section level2" number="12.4">
<h2>
<span class="header-section-number">12.4</span> Data and hypotheses<a class="anchor" aria-label="anchor" href="#data-and-hypotheses-5"><i class="fas fa-link"></i></a>
</h2>
<p>For example, suppose we measure the feeding rate of oyster catchers (shellfish per hour) at three sites characterised by their degree of shelter from the wind, imaginatively called <code>exposed</code> (E), <code>partially sheltered</code> (P) and <code>sheltered</code> (S). We want to test whether the data support the hypothesis that feeding rates don’t differ between locations. We form the following null and alternative hypotheses:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: The mean feeding rates at all three sites is the same <span class="math inline">\(\mu E = \mu P = \mu S\)</span>
</li>
<li>
<span class="math inline">\(H_1\)</span>: The mean feeding rates are not all equal.</li>
</ul>
<p>We will use a one-way ANOVA test to check this.</p>
<ul>
<li>We use a <strong>one-way</strong> ANOVA test because we only have one predictor variable (the categorical variable location).</li>
<li>We’re using <strong>ANOVA</strong> because we have more than two groups and we don’t know any better yet with respect to the exact assumptions.</li>
</ul>
<p>The data are stored in the file <code>CS2-oystercatcher.csv</code>.</p>
</div>
<div id="summarise-and-visualise-6" class="section level2" number="12.5">
<h2>
<span class="header-section-number">12.5</span> Summarise and visualise<a class="anchor" aria-label="anchor" href="#summarise-and-visualise-6"><i class="fas fa-link"></i></a>
</h2>
<p>First we read in the data.</p>
<div class="sourceCode" id="cb91"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># load data</span>
<span class="va">oystercatcher</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS2-oystercatcher.csv"</span><span class="op">)</span>

<span class="co"># and have a look</span>
<span class="va">oystercatcher</span></code></pre></div>
<pre><code>## # A tibble: 15 × 3
##       id feeding site     
##    &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;    
##  1     1    14.2 Exposed  
##  2     2    16.5 Exposed  
##  3     3     9.3 Exposed  
##  4     4    15.1 Exposed  
##  5     5    13.4 Exposed  
##  6     6    18.4 Partial  
##  7     7    13   Partial  
##  8     8    17.4 Partial  
##  9     9    20.4 Partial  
## 10    10    16.5 Partial  
## 11    11    24.1 Sheltered
## 12    12    22.2 Sheltered
## 13    13    25.3 Sheltered
## 14    14    25.1 Sheltered
## 15    15    21.5 Sheltered</code></pre>
<p>The <code>oystercatcher</code> data set contains three columns:</p>
<ol style="list-style-type: decimal">
<li>a unique ID column <code>id</code>
</li>
<li>a <code>feeding</code> column containing feeding rates</li>
<li>a <code>site</code> column with information on the amount of shelter of the feeding location</li>
</ol>
<p>First, we get some basic descriptive statistics:</p>
<div class="sourceCode" id="cb93"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># get some basic descriptive statistics</span>
<span class="va">oystercatcher</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">id</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">site</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/get_summary_stats.html">get_summary_stats</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">"common"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 11
##   site      variable     n   min   max median   iqr  mean    sd    se    ci
##   &lt;chr&gt;     &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Exposed   feeding      5   9.3  16.5   14.2   1.7  13.7  2.72 1.21   3.37
## 2 Partial   feeding      5  13    20.4   17.4   1.9  17.1  2.73 1.22   3.39
## 3 Sheltered feeding      5  21.5  25.3   24.1   2.9  23.6  1.71 0.767  2.13</code></pre>
<p>Next, we plot the data by <code>site</code>:</p>
<div class="sourceCode" id="cb95"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># plot the data</span>
<span class="va">oystercatcher</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">site</span>, y <span class="op">=</span> <span class="va">feeding</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs2-practical-anova_files/figure-html/unnamed-chunk-5-1.png" width="672"></div>
<p>Looking at the data, there appears to be a noticeable difference in feeding rates between the three sites. We would probably expect a reasonably significant statistical result here.</p>
</div>
<div id="assumptions-11" class="section level2" number="12.6">
<h2>
<span class="header-section-number">12.6</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-11"><i class="fas fa-link"></i></a>
</h2>
<p>To use an ANOVA test, we have to make three assumptions:</p>
<ol style="list-style-type: decimal">
<li>The parent distributions from which the samples are taken are normally distributed</li>
<li>Each data point in the samples is independent of the others</li>
<li>The parent distributions should have the same variance</li>
</ol>
<p>In a similar way to the two-sample tests we will consider the normality and equality of variance assumptions both using tests and by graphical inspection (and ignore the independence assumption).</p>
<div id="normality" class="section level3" number="12.6.1">
<h3>
<span class="header-section-number">12.6.1</span> Normality<a class="anchor" aria-label="anchor" href="#normality"><i class="fas fa-link"></i></a>
</h3>
<p>First we perform a Shapiro-Wilk test on each site separately.</p>
<div class="sourceCode" id="cb96"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Shapiro-Wilk test on each site</span>
<span class="va">oystercatcher</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">id</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">site</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/shapiro_test.html">shapiro_test</a></span><span class="op">(</span><span class="va">feeding</span><span class="op">)</span></code></pre></div>
<p>We can see that all three groups appear to be normally distributed which is good.</p>
<p>For ANOVA however, considering each group in turn is often considered quite excessive and, in most cases, it is sufficient to consider the normality of the combined set of <em>residuals</em> from the data. We’ll explain residuals properly in the <a href="cs3-intro.html#cs3-intro">next session</a> but effectively they are the difference between each data point and its group mean. The residuals can be obtained directly from a linear model fitted to the data.</p>
<p>So, we create a linear model, extract the residuals and check their normality:</p>
<div class="sourceCode" id="cb97"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># define the model</span>
<span class="va">lm_oystercatcher</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">feeding</span> <span class="op">~</span> <span class="va">site</span>,
                       data <span class="op">=</span> <span class="va">oystercatcher</span><span class="op">)</span>

<span class="co"># extract the residuals</span>
<span class="va">resid_oyster</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">lm_oystercatcher</span><span class="op">)</span>

<span class="co"># perform Shapiro-Wilk test on residuals</span>
<span class="va">resid_oyster</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/shapiro_test.html">shapiro_test</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   variable statistic p.value
##   &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt;
## 1 .            0.936   0.334</code></pre>
<p>Again, we can see that the combined residuals from all three groups appear to be normally distributed (which is as we would have expected given that they were all normally distributed individually!)</p>
</div>
<div id="equality-of-variance-1" class="section level3" number="12.6.2">
<h3>
<span class="header-section-number">12.6.2</span> Equality of Variance<a class="anchor" aria-label="anchor" href="#equality-of-variance-1"><i class="fas fa-link"></i></a>
</h3>
<p>We now test for equality of variance using Bartlett’s test (since we’ve just found that all of the individual groups are normally distributed).</p>
<p>Perform Bartlett’s test on the data:</p>
<div class="sourceCode" id="cb99"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># check equality of variance</span>
<span class="fu"><a href="https://rdrr.io/r/stats/bartlett.test.html">bartlett.test</a></span><span class="op">(</span><span class="va">feeding</span> <span class="op">~</span> <span class="va">site</span>,
              data <span class="op">=</span> <span class="va">oystercatcher</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  feeding by site
## Bartlett's K-squared = 0.90632, df = 2, p-value = 0.6356</code></pre>
<p>Where the relevant p-value is given on the 3rd line. Here we see that each group do appear to have the same variance.</p>
</div>
<div id="graphical-interpretation-and-diagnostic-plots" class="section level3" number="12.6.3">
<h3>
<span class="header-section-number">12.6.3</span> Graphical interpretation and diagnostic Plots<a class="anchor" aria-label="anchor" href="#graphical-interpretation-and-diagnostic-plots"><i class="fas fa-link"></i></a>
</h3>
<p>R provides a convenient set of graphs that allow us to assess these assumptions graphically. If we simply ask R to plot the <code>lm</code> object we have created, then we can see some of these <em>diagnostic plots</em>.</p>
<div class="note">
<p>There are a variety of ways that we can create diagnostic plots. There is no right or wrong - just preference.</p>
<p>The functionality of <strong>base R</strong> is really helpful, and it’s easy to create diagnostic plots with the built-in functionality. For example, you can create a set of basic diagnostic plots using:</p>
<pre><code># create a neat 2x2 window
par(mfrow = c(2,2))
# create the diagnostic plots
plot(model_name)
# and return the window back to normal
par(mfrow = c(1,1))</code></pre>
<p>In the first session we already created diagnostic Q-Q plots directly from our data, using <code><a href="https://ggplot2.tidyverse.org/reference/geom_qq.html">stat_qq()</a></code> and <code><a href="https://ggplot2.tidyverse.org/reference/geom_qq.html">stat_qq_line()</a></code>. For more specific plots this becomes a bit cumbersome. There is an option to create ggplot-friendly diagnostic plots, using the <code>ggResidPanel</code> package. For consistency with the <code>tidyverse</code> syntax used, we will use this from now on, but it is equally valid to use the base R functions.</p>
</div>
<p>Create the standard set diagnostic plots using <code>ggResidPanel</code>:</p>
<div class="sourceCode" id="cb102"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lm_oystercatcher</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs2-practical-anova_files/figure-html/cs2-anova-oyster-diagnostic-1.png" width="672"></div>
<ul>
<li>
<strong>Residual Plot</strong>: creates a plot of the residuals versus the predicted values. We want the points to be spread symmetrically around the blue line.</li>
<li>
<strong>Q-Q Plot</strong>: creates a normal quantile plot of residuals</li>
<li>
<strong>Index Plot</strong>: creates a plot of the residuals versus the observation numbers. A solid blue horizontal line through 0 is included for reference. This plot can be used to look for patterns in the data</li>
<li>
<strong>Histogram</strong>: creates a histogram of the residuals, using <code>bins = 30</code> as default</li>
</ul>
<p>The default equivalent in base R is as follows:</p>
<div class="sourceCode" id="cb103"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a neat 2x2 window</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span>
<span class="co"># create the diagnostic plots</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lm_oystercatcher</span><span class="op">)</span></code></pre></div>
<pre><code>## hat values (leverages) are all = 0.2
##  and there are no factor predictors; no plot no. 5</code></pre>
<div class="inline-figure"><img src="cs2-practical-anova_files/figure-html/cs2-anova-oyster-diagnostic-results-1.png" width="672"></div>
<div class="sourceCode" id="cb105"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># and return the window back to normal</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>The second line creates the three diagnostic plots (it actually tries to create four plots but can’t do that for this dataset so you’ll also see some warning text output to the screen (something about hat values). I’ll go through this in the next session where it’s easier to explain).</p>
<ul>
<li>In this example, two of the plots (top-left and bottom-left) show effectively the same thing: what the distribution of data between each group look like. These allow an informal check on the equality of variance assumption.
<ul>
<li>For the top-left graph we want all data to be symmetric about the 0 horizontal line and for the spread to be the same (please ignore the red line; it is an unhelpful addition to these graphs).</li>
<li>For the bottom-left graph, we will look at the red line as we want it to be approximately horizontal.</li>
</ul>
</li>
<li>The top-right graph is a familiar Q-Q plot that we used previously to assess normality, and this looks at the combined residuals from all of the groups (in much the same way as we looked at the Shapiro-Wilk test on the combined residuals).</li>
</ul>
<p>We can see that these graphs are very much in line with what we’ve just looked at using the test, which is reassuring. The groups all appear to have the same spread of data, and whilst the Q-Q plot isn’t perfect, it appears that the assumption of normality is alright.</p>
<div class="note">
<p>At this stage, I should point out that I nearly always stick with the graphical method for assessing the assumptions of a test. Assumptions are rarely either completely met or not met and there is always some degree of personal assessment.</p>
<p>Whilst the formal statistical tests (like Shapiro) are technically fine, they can often create a false sense of things being absolutely right or wrong in spite of the fact that they themselves are still probabilistic statistical tests. In these exercises we are using both approaches whilst you gain confidence and experience in interpreting the graphical output and whilst it is absolutely fine to use both in the future I would strongly recommend that you don’t rely solely on the statistical tests in isolation.</p>
</div>
</div>
</div>
<div id="implement-test-5" class="section level2" number="12.7">
<h2>
<span class="header-section-number">12.7</span> Implement test<a class="anchor" aria-label="anchor" href="#implement-test-5"><i class="fas fa-link"></i></a>
</h2>
<p>Perform an ANOVA test on the data:</p>
<div class="sourceCode" id="cb106"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm_oystercatcher</span><span class="op">)</span></code></pre></div>
<p>The first line fits a linear model to the data (i.e. finds the means of the three groups and calculates a load of intermediary data that we need for the statistical analysis) and stores this information in an R object (which I’ve called <code>lm_oystercatchers</code>, but which you can call what you like). The second line actually carries out the ANOVA analysis.</p>
<ul>
<li>The first argument must be in the formula format: <code>response ~ predictor</code>
</li>
<li>If the data are stored in stacked format, then the second argument must be the name of the data frame</li>
<li>The <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> command takes a linear model object as its main argument</li>
</ul>
</div>
<div id="interpret-output-and-report-results-4" class="section level2" number="12.8">
<h2>
<span class="header-section-number">12.8</span> Interpret output and report results<a class="anchor" aria-label="anchor" href="#interpret-output-and-report-results-4"><i class="fas fa-link"></i></a>
</h2>
<p>This is the output that you should now see in the console window:</p>
<pre><code>## Analysis of Variance Table
## 
## Response: feeding
##           Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## site       2 254.812 127.406  21.508 0.0001077 ***
## Residuals 12  71.084   5.924                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<ul>
<li>The 1st line just tells you the that this is an ANOVA test</li>
<li>The 2nd line tells you what the response variable is (in this case feeding)</li>
<li>The 3rd, 4th and 5th lines are an ANOVA table which contain some useful values:
<ul>
<li>The <code>Df</code> column contains the degrees of freedom values on each row, 2 and 12 (which we’ll need for the reporting)</li>
<li>The <code>F</code> value column contains the F statistic, 21.508 (which again we’ll need for reporting).</li>
<li>The p-value is 0.0001077 and is the number directly under the <code>Pr(&gt;F)</code> on the 4th line.</li>
<li>The other values in the table (in the <code>Sum Sq</code> and <code>Mean Sq</code>) columns are used to calculate the F statistic itself and we don’t need to know these.</li>
</ul>
</li>
<li>The 6th line has some symbolic codes to represent how big (small) the p-value is; so, a p-value smaller than 0.001 would have a *** symbol next to it (which ours does). Whereas if the p-value was between 0.01 and 0.05 then there would simply be a * character next to it, etc. Thankfully we can all cope with actual numbers and don’t need a short-hand code to determine the reporting of our experiments (please tell me that’s true…!)</li>
</ul>
<p>Again, the p-value is what we’re most interested in here and shows us the probability of getting samples such as ours if the null hypothesis were actually true.</p>
<p>Since the p-value is very small (much smaller than the standard significance level of 0.05) we can say “that it is very unlikely that these three samples came from the same parent distribution” and as such we can reject our null hypothesis and state that:</p>
<blockquote>
<p>A one-way ANOVA showed that the mean feeding rate of oystercatchers differed significantly between locations (F = 21.51, df = 2, 12, p = 0.00011).</p>
</blockquote>
<p>Note that we have included (in brackets) information on the test statistic (F = 21.51), both degrees of freedom (df = 2, 12), and the p-value (p = 0.00011).</p>
</div>
<div id="post-hoc-testing-tukeys-rank-test" class="section level2" number="12.9">
<h2>
<span class="header-section-number">12.9</span> Post-hoc testing (Tukey’s rank test)<a class="anchor" aria-label="anchor" href="#post-hoc-testing-tukeys-rank-test"><i class="fas fa-link"></i></a>
</h2>
<p>One drawback with using an ANOVA test is that it only tests to see if all of the means are the same, and if we get a significant result using ANOVA then all we can say is that not all of the means are the same, rather than anything about how the pairs of groups differ. For example, consider the following boxplot for three samples.</p>
<div class="inline-figure"><img src="cs2-practical-anova_files/figure-html/unnamed-chunk-8-1.png" width="672"></div>
<p>Each group is a random sample of 20 points from a normal distribution with variance 1. Groups 1 and 2 come from a parent population with mean 0 whereas group 3 come from a parent population with mean 2. The data clearly satisfy the assumptions of an ANOVA test.</p>
<div id="read-in-the-data-and-plot" class="section level3" number="12.9.1">
<h3>
<span class="header-section-number">12.9.1</span> Read in the data and plot<a class="anchor" aria-label="anchor" href="#read-in-the-data-and-plot"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># load the data</span>
<span class="va">tukey</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS2-tukey.csv"</span><span class="op">)</span>

<span class="co"># have a look at the data</span>
<span class="va">tukey</span></code></pre></div>
<pre><code>## # A tibble: 60 × 3
##       id response group  
##    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;  
##  1     1    1.58  sample1
##  2     2    0.380 sample1
##  3     3   -0.997 sample1
##  4     4   -0.771 sample1
##  5     5    0.169 sample1
##  6     6   -0.698 sample1
##  7     7   -0.167 sample1
##  8     8    1.38  sample1
##  9     9   -0.839 sample1
## 10    10   -1.05  sample1
## # … with 50 more rows</code></pre>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># plot the data</span>
<span class="va">tukey</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">group</span>, y <span class="op">=</span> <span class="va">response</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs2-practical-anova_files/figure-html/unnamed-chunk-9-1.png" width="672"></div>
</div>
<div id="test-for-a-significant-difference-in-group-means" class="section level3" number="12.9.2">
<h3>
<span class="header-section-number">12.9.2</span> Test for a significant difference in group means<a class="anchor" aria-label="anchor" href="#test-for-a-significant-difference-in-group-means"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a linear model</span>
<span class="va">lm_tukey</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">response</span> <span class="op">~</span> <span class="va">group</span>,
               data <span class="op">=</span> <span class="va">tukey</span><span class="op">)</span>

<span class="co"># perform an ANOVA</span>
<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm_tukey</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: response
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## group      2 33.850 16.9250   20.16 2.392e-07 ***
## Residuals 57 47.854  0.8395                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>Here we have a p-value of 2.39 <span class="math inline">\(\cdot\)</span> 10<sup>-7</sup> and so the test has very conclusively rejected the hypothesis that all means are equal.</p>
<p>However, this was not due to all of the sample means being different, but rather just because one of the groups is very different from the others. In order to drill down and investigate this further we use a new test called <strong>Tukey’s range test</strong> (or <strong>Tukey’s honest significant difference test</strong> – this always makes me think of some terrible cowboy/western dialogue). This will compare all of the groups in a pairwise fashion and reports on whether a significant difference exists.</p>
</div>
<div id="performing-tukeys-test" class="section level3" number="12.9.3">
<h3>
<span class="header-section-number">12.9.3</span> Performing Tukey’s test<a class="anchor" aria-label="anchor" href="#performing-tukeys-test"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb113"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># perform Tukey's range test on linear model</span>
<span class="va">lm_tukey</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/tukey_hsd.html">tukey_hsd</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 9
##   term  group1  group2  null.value estimate conf.low conf.high       p.adj
## * &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 group sample1 sample2          0    0.304   -0.393      1.00 0.55       
## 2 group sample1 sample3          0    1.72     1.03       2.42 0.000000522
## 3 group sample2 sample3          0    1.42     0.722      2.12 0.0000246  
## # … with 1 more variable: p.adj.signif &lt;chr&gt;</code></pre>
<p>The <code><a href="https://rpkgs.datanovia.com/rstatix/reference/tukey_hsd.html">tukey_hsd()</a></code> function takes our linear model (<code>lm_tukey</code>) as its input. The output is a pair-by-pair comparison between the different groups (samples 1 to 3). We are interested in the <code>p.adj</code> column, which gives us the adjusted p-value. The null hypothesis in each case is that there is no difference in the mean between the two groups. As we can see the first row shows that there isn’t a significant difference between <code>sample1</code> and <code>sample2</code> but the 2nd and 3rd rows show that there is a significant difference between <code>sample1</code> and <code>sample3</code>, as well as <code>sample2</code> and <code>sample3</code>. This matches with what we expected based on the boxplot.</p>
</div>
<div id="assumptions-12" class="section level3" number="12.9.4">
<h3>
<span class="header-section-number">12.9.4</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-12"><i class="fas fa-link"></i></a>
</h3>
<p>When to use Tukey’s range test is a matter of debate (strangely enough a lot of statistical analysis techniques are currently matters of opinion rather than mathematical fact – it does explain a little why this whole field appears so bloody confusing!)</p>
<ul>
<li>Some people claim that we should only perform Tukey’s range test (or any other post-hoc tests) if the preceding ANOVA test showed that there was a significant difference between the groups and that if the ANOVA test had not shown any significant differences between groups then we would have to stop there.</li>
<li>Other people say that this is rubbish and we can do what the hell we like, when we like as long as we tell people what we did.</li>
</ul>
<p>The background to this is rather involved but one of the reasons for this debate is to prevent so-called <strong>data-dredging</strong> or <strong>p-hacking</strong>. This is where scientists/analysts are so fixated on getting a “significant” result that they perform a huge variety of statistical techniques until they find one that shows that their data is significant (this was a particular problem in psychological studies for while – not to point fingers though, they are working hard to sort their stuff out. Kudos!).</p>
<p>Whether you should use post-hoc testing or not will depend on your experimental design and the questions that you’re attempting to answer.</p>
<p>Tukey’s range test, when we decide to use it, requires the same three assumptions as an ANOVA test:</p>
<ol style="list-style-type: decimal">
<li>Normality of distributions</li>
<li>Equality of variance between groups</li>
<li>Independence of observations</li>
</ol>
</div>
</div>
<div id="exercise-lobster-weight" class="section level2" number="12.10">
<h2>
<span class="header-section-number">12.10</span> Exercise: Lobster weight<a class="anchor" aria-label="anchor" href="#exercise-lobster-weight"><i class="fas fa-link"></i></a>
</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-8" class="exercise"><strong>Exercise 12.1  </strong></span>Juvenile lobster weight</p>
<p>Juvenile lobsters in aquaculture were grown on three different diets (fresh mussels, semi-dry pellets and dry flakes). After nine weeks, their wet weight was:</p>
<div class="inline-table"><table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:right;">
Mussels
</th>
<th style="text-align:right;">
Pellets
</th>
<th style="text-align:right;">
Flakes
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
151.6
</td>
<td style="text-align:right;">
117.7
</td>
<td style="text-align:right;">
101.8
</td>
</tr>
<tr>
<td style="text-align:right;">
132.1
</td>
<td style="text-align:right;">
110.8
</td>
<td style="text-align:right;">
102.9
</td>
</tr>
<tr>
<td style="text-align:right;">
104.2
</td>
<td style="text-align:right;">
128.6
</td>
<td style="text-align:right;">
90.4
</td>
</tr>
<tr>
<td style="text-align:right;">
153.5
</td>
<td style="text-align:right;">
110.1
</td>
<td style="text-align:right;">
132.8
</td>
</tr>
<tr>
<td style="text-align:right;">
132.0
</td>
<td style="text-align:right;">
175.2
</td>
<td style="text-align:right;">
129.3
</td>
</tr>
<tr>
<td style="text-align:right;">
119.0
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
129.4
</td>
</tr>
<tr>
<td style="text-align:right;">
161.9
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table></div>
<p>Is there any evidence that diet affects the growth rate of lobsters?</p>
<ol style="list-style-type: decimal">
<li>Write down the null and alternative hypotheses</li>
<li>Import the data into R
<ul>
<li>The data are stored in a tidy format in <code>data/tidy/CS2-lobsters.csv</code>
</li>
</ul>
</li>
<li>Summarise and visualise the data</li>
<li>Check the assumptions using appropriate tests and graphical analyses</li>
<li>Perform an ANOVA test</li>
<li>Write down a sentence that summarise the results that you have found</li>
<li>Perform a post-hoc test and report the findings</li>
</ol>
<details><summary>
Answer
</summary><div id="hypotheses-5" class="section level3" number="12.10.1">
<h3>
<span class="header-section-number">12.10.1</span> Hypotheses<a class="anchor" aria-label="anchor" href="#hypotheses-5"><i class="fas fa-link"></i></a>
</h3>
<p><span class="math inline">\(H_0\)</span> : all means are equal</p>
<p><span class="math inline">\(H_1\)</span> : not all means are equal</p>
</div>
<div id="import-data-summarise-and-visualise-1" class="section level3" number="12.10.2">
<h3>
<span class="header-section-number">12.10.2</span> Import Data, summarise and visualise<a class="anchor" aria-label="anchor" href="#import-data-summarise-and-visualise-1"><i class="fas fa-link"></i></a>
</h3>
<p>The data are stored in a <code>.csv</code> file with columns called <code>id</code>, <code>weight</code> and <code>diet</code>.</p>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># load the data</span>
<span class="va">lobsters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/tidy/CS2-lobsters.csv"</span><span class="op">)</span>

<span class="co"># look at the data</span>
<span class="va">lobsters</span></code></pre></div>
<pre><code>## # A tibble: 18 × 3
##       id weight diet   
##    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;  
##  1     1  152.  Mussels
##  2     2  132.  Mussels
##  3     3  104.  Mussels
##  4     4  154.  Mussels
##  5     5  132   Mussels
##  6     6  119   Mussels
##  7     7  162.  Mussels
##  8     8  118.  Pellets
##  9     9  111.  Pellets
## 10    10  129.  Pellets
## 11    11  110.  Pellets
## 12    12  175.  Pellets
## 13    13  102.  Flakes 
## 14    14  103.  Flakes 
## 15    15   90.4 Flakes 
## 16    16  133.  Flakes 
## 17    17  129.  Flakes 
## 18    18  129.  Flakes</code></pre>
<div class="sourceCode" id="cb117"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create some summary statistics</span>
<span class="va">lobsters</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">id</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">diet</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/get_summary_stats.html">get_summary_stats</a></span><span class="op">(</span>type <span class="op">=</span> <span class="st">"common"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 11
##   diet    variable     n   min   max median   iqr  mean    sd    se    ci
##   &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Flakes  weight       6  90.4  133.   116.  27.3  114.  18.2  7.42  19.1
## 2 Mussels weight       7 104.   162.   132.  27.0  136.  20.6  7.79  19.1
## 3 Pellets weight       5 110.   175.   118.  17.8  128.  27.2 12.1   33.7</code></pre>
<p>Next, we visualise the data:</p>
<div class="sourceCode" id="cb119"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lobsters</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">diet</span>, y <span class="op">=</span> <span class="va">weight</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs2-practical-anova_files/figure-html/unnamed-chunk-15-1.png" width="672"></div>
<p>As always we use the plot and summary to assess three things:</p>
<ol style="list-style-type: decimal">
<li>Did we load the data in properly?</li>
</ol>
<ul>
<li>We see three groups with reasonable values. There aren’t any data points that are obviously wrong (negative, zero or massively big) and we have the right number of groups. So it looks as if we didn’t do anything obviously wrong.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>What do we expect as a result of a statistical test?</li>
</ol>
<ul>
<li>Whilst the <code>Mussels</code> group does look higher than the other two groups, <code>Pellets</code> and <code>Flakes</code> appear almost identical in terms of average values, and there’s quite a bit of overlap with the <code>Mussels</code> group. A non-significant result is the most likely answer, and I would be surprised to see a significant p-value - especially given the small sample size that we have here.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>What do we think about assumptions?</li>
</ol>
<ul>
<li>The groups appear mainly symmetric (although <code>Pellets</code> is a bit weird) and so we’re not immediately massively worried about lack of normality. Again, <code>Flakes</code> and <code>Mussels</code> appear to have very similar variances but it’s a bit hard to decide what’s going on with <code>Pellets.</code> It’s hard to say what’s going on with the assumptions and so I’ll wait and see what the other tests say.</li>
</ul>
</div>
<div id="explore-assumptions" class="section level3" number="12.10.3">
<h3>
<span class="header-section-number">12.10.3</span> Explore Assumptions<a class="anchor" aria-label="anchor" href="#explore-assumptions"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Normality</strong></p>
<p>We’ll be really thorough here and consider the normality of each group separately and jointly using the Shapiro-Wilk test, as well as looking at the Q-Q plot. In reality, and after these examples , we’ll only use the Q-Q plot.</p>
<p>First, we perform the Shapiro-Wilk test on the individual groups:</p>
<div class="sourceCode" id="cb120"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Shapiro-Wilk on lobster groups</span>
<span class="va">lobsters</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">diet</span><span class="op">)</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/shapiro_test.html">shapiro_test</a></span><span class="op">(</span><span class="va">weight</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 4
##   diet    variable statistic      p
##   &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;
## 1 Flakes  weight       0.844 0.140 
## 2 Mussels weight       0.948 0.710 
## 3 Pellets weight       0.767 0.0425</code></pre>
<p><code>Flakes</code> and <code>Mussels</code> are fine, but, as we suspected from earlier, <code>Pellets</code> appears to have a marginally significant Normality test result.</p>
<p>Let’s look at the Shapiro-Wilk test for all of the data together:</p>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a linear model</span>
<span class="va">lm_lobsters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">diet</span>,
                  data <span class="op">=</span> <span class="va">lobsters</span><span class="op">)</span>

<span class="co"># extract the residuals</span>
<span class="va">resid_lobsters</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">lm_lobsters</span><span class="op">)</span>

<span class="co"># and perform the Shapiro-Wilk test on the residuals</span>
<span class="va">resid_lobsters</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/shapiro_test.html">shapiro_test</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   variable statistic p.value
##   &lt;chr&gt;        &lt;dbl&gt;   &lt;dbl&gt;
## 1 .            0.948   0.391</code></pre>
<p>This on the other hand says that everything is fine. Let’s look at Q-Q plot.</p>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Q-Q plots</span>
<span class="va">lm_lobsters</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel</a></span><span class="op">(</span>plots <span class="op">=</span> <span class="st">"qq"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs2-practical-anova_files/figure-html/unnamed-chunk-18-1.png" width="672"></div>
<p>Here, I’ve used an extra argument to the normal diagnostic plots call. The default option is to plot 4 diagnostic plots. You can tell <code><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel()</a></code> to only plot a specific one, using the <code>plots =</code> arguments. If you want to know more about this have a look at the <a href="https://goodekat.github.io/ggResidpanel-tutorial/tutorial.html#overview">help documentation</a> or by using <code><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">?resid_panel</a></code>.</p>
<p>The Q-Q plot looks OK, not perfect, but more than good enough for us to have confidence in the normality of the data.</p>
<p>Overall, I’d be happy that the assumption of normality has been adequately well met here. The suggested lack of normality in the <code>Pellets</code> was only just significant and we have to take into account that there are only 5 data points in that group. If there had been a lot more points in that group, or if the Q-Q plot was considerably worse then I wouldn’t be confident.</p>
<p><strong>Equality of Variance</strong></p>
<p>We’ll consider the Bartlett test and we’ll look at some diagnostic plots too.</p>
<div class="sourceCode" id="cb125"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># perform Bartlett's test</span>
<span class="fu"><a href="https://rdrr.io/r/stats/bartlett.test.html">bartlett.test</a></span><span class="op">(</span><span class="va">weight</span> <span class="op">~</span> <span class="va">diet</span>,
              data <span class="op">=</span> <span class="va">lobsters</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  weight by diet
## Bartlett's K-squared = 0.71273, df = 2, p-value = 0.7002</code></pre>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># plot the residuals and scale-location plots</span>
<span class="va">lm_lobsters</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel</a></span><span class="op">(</span>plots <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"resid"</span>, <span class="st">"ls"</span><span class="op">)</span>,
              smoother <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs2-practical-anova_files/figure-html/unnamed-chunk-19-1.png" width="672"></div>
<p>In the above code I’ve specified which diagnostic plots I wanted. I have also added a loess smoother line (<code>smoother = TRUE</code>) to the plots</p>
<ol style="list-style-type: decimal">
<li>The Residuals Plot. What we’re looking for there is that the points are evenly spread on either side of the line. Looks good.</li>
<li>The Location-Scale Plot (this is displayed by default in base R’s diagnostic plots). Here we’re looking at the red line. If that line is more or less horizontal, then the equality of variance assumption is met.</li>
</ol>
<p>Here all three methods agree that there isn’t any issues with equality of variance:</p>
<ul>
<li>the Bartlett test p-value is large and non-significant</li>
<li>the spread of points in all three groups in the residuals vs fitted graph are roughly the same</li>
<li>the red line in the scale-location graph is pretty horizontal</li>
</ul>
<p>Overall, this assumption is pretty well met.</p>
</div>
<div id="carry-out-one-way-anova" class="section level3" number="12.10.4">
<h3>
<span class="header-section-number">12.10.4</span> Carry out one-way ANOVA<a class="anchor" aria-label="anchor" href="#carry-out-one-way-anova"><i class="fas fa-link"></i></a>
</h3>
<p>With our assumptions of normality and equality of variance met we can be confident that a one-way ANOVA is an appropriate test.</p>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm_lobsters</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: weight
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## diet       2 1567.2  783.61  1.6432 0.2263
## Residuals 15 7153.1  476.87</code></pre>
</div>
<div id="result" class="section level3" number="12.10.5">
<h3>
<span class="header-section-number">12.10.5</span> Result<a class="anchor" aria-label="anchor" href="#result"><i class="fas fa-link"></i></a>
</h3>
<blockquote>
<p>A one-way ANOVA test indicated that the mean weight of juvenile lobsters did not differ significantly between diets (F = 1.64, df = 2,15, p = 0.23).</p>
</blockquote>
<p><br></p>
</div>
<div id="post-hoc-testing-with-tukey" class="section level3" number="12.10.6">
<h3>
<span class="header-section-number">12.10.6</span> Post-hoc testing with Tukey<a class="anchor" aria-label="anchor" href="#post-hoc-testing-with-tukey"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lm_lobsters</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rpkgs.datanovia.com/rstatix/reference/tukey_hsd.html">tukey_hsd</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 9
##   term  group1  group2 null.value estimate conf.low conf.high p.adj p.adj.signif
## * &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       
## 1 diet  Flakes  Musse…          0    21.9     -9.66      53.5 0.202 ns          
## 2 diet  Flakes  Pelle…          0    14.0    -20.3       48.4 0.551 ns          
## 3 diet  Mussels Pelle…          0    -7.85   -41.1       25.4 0.815 ns</code></pre>
<p>Here we can see that actually, there is no significant difference between any of the pairs of groups in this dataset.</p>
<div class="note">
<p>I want to reiterate that carrying out the post-hoc test after getting a non-significant result with ANOVA is something that you have to think very carefully about and it all depends on what your research question it.</p>
<p>If your research question was:</p>
<p><em>Does diet affect lobster weight?</em> or <em>Is there any effect of diet on lobster weight?</em></p>
<p>Then when we got the non-significant result from the ANOVA test we should have just stopped there as we have our answer. Going digging for “significant” results by running more tests is a main factor that contributes towards lack of reproducibility in research.</p>
<p>If on the other hand your research question was:</p>
<p><em>Are any specific diets better or worse for lobster weight than others?</em></p>
<p>Then we should probably have just skipped the one-way ANOVA test entirely and just jumped straight in with the Tukey’s range test, but the important point here is that the result of the one-way ANOVA test doesn’t preclude carrying out the Tukey test.</p>
</div>

</div>
</details>
</div>
</div>
<div id="key-points-2" class="section level2" number="12.11">
<h2>
<span class="header-section-number">12.11</span> Key points<a class="anchor" aria-label="anchor" href="#key-points-2"><i class="fas fa-link"></i></a>
</h2>
<div class="keypoints">
<ul>
<li>We use an ANOVA to test if there is a difference in means between multiple continuous variables</li>
<li>In R we first define a linear model with <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code>, using the format <code>response ~ predictor</code>
</li>
<li>Next, we perform an ANOVA on the linear model with <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code>
</li>
<li>We check assumptions with diagnostic plots and check if the residuals are normally distributed</li>
<li>We use post-hoc testing to check for significant differences in the group means, for example using Tukey’s range test</li>
</ul>
</div>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="introduction-1.html"><span class="header-section-number">11</span> Introduction</a></div>
<div class="next"><a href="kruskal-wallis-test.html"><span class="header-section-number">13</span> Kruskal-Wallis test</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#cs2-anova"><span class="header-section-number">12</span> ANOVA</a></li>
<li><a class="nav-link" href="#objectives-2"><span class="header-section-number">12.1</span> Objectives</a></li>
<li><a class="nav-link" href="#purpose-and-aim-2"><span class="header-section-number">12.2</span> Purpose and aim</a></li>
<li><a class="nav-link" href="#section-commands-6"><span class="header-section-number">12.3</span> Section commands</a></li>
<li><a class="nav-link" href="#data-and-hypotheses-5"><span class="header-section-number">12.4</span> Data and hypotheses</a></li>
<li><a class="nav-link" href="#summarise-and-visualise-6"><span class="header-section-number">12.5</span> Summarise and visualise</a></li>
<li>
<a class="nav-link" href="#assumptions-11"><span class="header-section-number">12.6</span> Assumptions</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#normality"><span class="header-section-number">12.6.1</span> Normality</a></li>
<li><a class="nav-link" href="#equality-of-variance-1"><span class="header-section-number">12.6.2</span> Equality of Variance</a></li>
<li><a class="nav-link" href="#graphical-interpretation-and-diagnostic-plots"><span class="header-section-number">12.6.3</span> Graphical interpretation and diagnostic Plots</a></li>
</ul>
</li>
<li><a class="nav-link" href="#implement-test-5"><span class="header-section-number">12.7</span> Implement test</a></li>
<li><a class="nav-link" href="#interpret-output-and-report-results-4"><span class="header-section-number">12.8</span> Interpret output and report results</a></li>
<li>
<a class="nav-link" href="#post-hoc-testing-tukeys-rank-test"><span class="header-section-number">12.9</span> Post-hoc testing (Tukey’s rank test)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#read-in-the-data-and-plot"><span class="header-section-number">12.9.1</span> Read in the data and plot</a></li>
<li><a class="nav-link" href="#test-for-a-significant-difference-in-group-means"><span class="header-section-number">12.9.2</span> Test for a significant difference in group means</a></li>
<li><a class="nav-link" href="#performing-tukeys-test"><span class="header-section-number">12.9.3</span> Performing Tukey’s test</a></li>
<li><a class="nav-link" href="#assumptions-12"><span class="header-section-number">12.9.4</span> Assumptions</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#exercise-lobster-weight"><span class="header-section-number">12.10</span> Exercise: Lobster weight</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#hypotheses-5"><span class="header-section-number">12.10.1</span> Hypotheses</a></li>
<li><a class="nav-link" href="#import-data-summarise-and-visualise-1"><span class="header-section-number">12.10.2</span> Import Data, summarise and visualise</a></li>
<li><a class="nav-link" href="#explore-assumptions"><span class="header-section-number">12.10.3</span> Explore Assumptions</a></li>
<li><a class="nav-link" href="#carry-out-one-way-anova"><span class="header-section-number">12.10.4</span> Carry out one-way ANOVA</a></li>
<li><a class="nav-link" href="#result"><span class="header-section-number">12.10.5</span> Result</a></li>
<li><a class="nav-link" href="#post-hoc-testing-with-tukey"><span class="header-section-number">12.10.6</span> Post-hoc testing with Tukey</a></li>
</ul>
</li>
<li><a class="nav-link" href="#key-points-2"><span class="header-section-number">12.11</span> Key points</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

					</div>
				</div>
				<!-- Related links -->
				<!--<div class="campl-column3 campl-secondary-content">
					<div class="campl-content-container">
						<div class="campl-heading-container">
							<h2>Related Links</h2>
						</div>
						<ul class='campl-unstyled-list campl-related-links'>
							<li><a href="#">Lorem ipsum dolor sit amet</a></li>
							<li><a href="#">Consectetur adipisicing elit</a></li>
							<li><a href="#">Sed do eiusmod tempor incididunt extra long wrapping on to two line</a></li>
							<li><a href="#">Labore et dolore magna aliqua</a></li>
							<li><a href="#">Ut enim ad minim veniam</a></li>
							<li><a href="#">Quis nostrud exercitation ullamco</a></li>
						</ul>
					</div>
					<div class="campl-content-container">
						<div class="campl-vertical-teaser campl-teaser campl-promo-teaser">
							<div class="campl-content-container campl-vertical-teaser-txt">
								<p class='campl-teaser-title'><a href="#">Promo teaser with title above</a></p>
							</div>
							<div class="campl-content-container campl-vertical-teaser-img">
								<a href="#" class="campl-teaser-img-link"><img alt=""  src="images/content/homepage-promo-placeholder.png" class="campl-scale-with-grid" /></a>
							</div>
							<div class="campl-content-container campl-vertical-teaser-txt clearfix">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
								<a href="#4" class="campl-secondary-cta campl-float-right">Read more</a>
							</div>
						</div>
					</div>
				</div>-->
			</div>
		</div>
		<div class="campl-row campl-local-footer">
			<div class="campl-wrap clearfix">
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Contact us</h3>
						 <div class="content">
						   <p>Bioinformatics Training Department of Genetics University of Cambridge Downing Street Cambridge CB2 3EH United Kingdom</p>
						   <h3>Contact:</h3> <a href="mailto:%20bioinfotraining@bio.cam.ac.uk">bioinfotraining@bio.cam.ac.uk</a>
						 </div>
					</div>
				</div>
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Bioinformatics Training</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/undergraduate">Undergraduate training</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate">Postgraduate training</a>
							</li>
						</ul>
</div>
				</div>
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Postgraduate Courses by Theme</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/programming">Basic Skills and Programming</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/services">Databases and Services</a>
							</li>
							<li>
							  <a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/specialized">Specialised Topics</a>
							</li>
						</ul>
</div>
				</div>
				<div class="campl-column3 campl-footer-navigation last">
					<div class="campl-content-container campl-navigation-list">
						<h3>About Bioinformatics Training</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about">About the Facility</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about/findus">How to find us</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about/visitors">Visiting Cambridge</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/privacy-and-cookie-policies">Privacy and Cookies policy</a>
							</li>
						</ul>
</div>
				</div>
			</div>
		</div>
	<div class="campl-row campl-global-footer">
		<div class="campl-wrap clearfix">
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-footer-logo">
					<img alt="University of Cambridge" src="images/interface/main-logo-small.png" height="38px;" class="campl-scale-with-grid"><p>© 2021 University of Cambridge</p>
						<ul class="campl-unstyled-list campl-global-footer-links">
<li>
								<a href="http://www.cam.ac.uk/university-a-z">University A-Z</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/contact-the-university">Contact the University</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-this-site/accessibility">Accessibility</a>
							</li>
							<li>
								<a href="http://www.admin.cam.ac.uk/univ/information/foi/">Freedom of information</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-this-site/terms-and-conditions">Terms and conditions</a>
							</li>
						</ul>
</div>
			</div>
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-navigation-list">

					<div class="link-list">
						<h3><a href="http://www.cam.ac.uk/study-at-cambridge">Study at Cambridge</a></h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="http://www.study.cam.ac.uk/undergraduate/">Undergraduate</a>
							</li>
							<li>
								<a href="http://www.graduate.study.cam.ac.uk/">Graduate</a>
							</li>
							<li>
								<a href="http://www.internationalstudents.cam.ac.uk">International students</a>
							</li>
							<li>
								<a href="http://www.ice.cam.ac.uk">Continuing education</a>
							</li>
							<li>
								<a href="http://www.epe.admin.cam.ac.uk/">Executive and professional education</a>
							</li>
							<li>
								<a href="http://www.educ.cam.ac.uk">Courses in education</a>
							</li>
						</ul>
</div>
				</div>
			</div>
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-navigation-list">
					<h3><a href="http://www.cam.ac.uk/about-the-university">About the University</a></h3>
					<ul class="campl-unstyled-list campl-page-children">
<li>
							<a href="http://www.cam.ac.uk/about-the-university/how-the-university-and-colleges-work">How the University and Colleges work</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/about-the-university/visiting-the-university">Visiting the University</a>
						</li>
						<li>
							<a href="http://map.cam.ac.uk">Map</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/news">News</a>
						</li>
						<li>
							<a href="http://www.admin.cam.ac.uk/whatson/">Events</a>
						</li>
						<li>
							<a href="http://www.jobs.cam.ac.uk">Jobs</a>
						</li>
						<li>
							<a href="https://www.philanthropy.cam.ac.uk/">Give to Cambridge</a>
						</li>
					</ul>
</div>
			</div>
			<div class="campl-column3 campl-footer-navigation last">
				<div class="campl-content-container campl-navigation-list">
					<h3><a href="http://www.cam.ac.uk/research">Research at Cambridge</a></h3>
					<ul class="campl-unstyled-list">
<li>
							<a href="http://www.cam.ac.uk/research/news">News</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/features">Features</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/discussion">Discussion</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/spotlight-on">Spotlight on...</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/research-at-cambridge">About research at Cambridge</a>
						</li>
					</ul>
</div>
			</div>
		</div>
	</div>
	<!-- .campl-global-footer ends -->

<!--[if lte IE 8]>
</div>
<![endif]-->

	<script type="text/javascript" src="javascripts/libs/ios-orientationchange-fix.js"></script><script type="text/javascript" src="javascripts/libs/jquery-min.js"></script><script type="text/javascript" src="javascripts/libs/modernizr.js"></script><script type="text/javascript" src="javascripts/custom.js"></script><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
