<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="no-js">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Chapter 17 Linear regression | Core Statistics in R</title>
<meta name="author" content="Matt Castle and Martin van Rongen">
<meta name="description" content="17.1 Objectives  Questions When should I use a linear regression? How do I interpret the results? Objectives Be able to perform a linear regression in R Use ANOVA to check if the slope of the...">
<meta name="generator" content="bookdown 0.25 with bs4_book()">
<meta property="og:title" content="Chapter 17 Linear regression | Core Statistics in R">
<meta property="og:type" content="book">
<meta property="og:description" content="17.1 Objectives  Questions When should I use a linear regression? How do I interpret the results? Objectives Be able to perform a linear regression in R Use ANOVA to check if the slope of the...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 17 Linear regression | Core Statistics in R">
<meta name="twitter:description" content="17.1 Objectives  Questions When should I use a linear regression? How do I interpret the results? Objectives Be able to perform a linear regression in R Use ANOVA to check if the slope of the...">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references --><link rel="shortcut icon" href="favicon.ico">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<!-- CSS : implied media="all" --><link rel="stylesheet" href="stylesheets/full-stylesheet.css">
<link rel="stylesheet" href="stylesheets/styleguide.css">
<link rel="stylesheet" href="stylesheets/style.css">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><script type="text/javascript" src="//use.typekit.com/hyb5bko.js"></script><script type="text/javascript">try{Typekit.load();}catch(e){}</script><script type="text/javascript">  document.documentElement.className += " js";</script>
</head>
<body class="campl-theme-2" data-spy="scroll" data-target="#toc">

<!--[if lt IE 7]>
<div class="lt-ie9 lt-ie8 lt-ie7">
<![endif]-->
<!--[if IE 7]>
<div class="lt-ie9 lt-ie8">
<![endif]-->
<!--[if IE 8]>
<div class="lt-ie9">
<![endif]-->

	<a href="#primary-nav" class="campl-skipTo">skip to primary navigation</a>
	<a href="#content" class="campl-skipTo">skip to content</a>
	<div class="campl-row campl-global-header">
		<div class="campl-wrap clearfix">
			<div class="campl-header-container campl-column8" id="global-header-controls">
				<a href="http://www.cam.ac.uk" class="campl-main-logo">
					<img alt="University of Cambridge" src="images/interface/main-logo-small.png" height="38px;"></a>

				<ul class="campl-unstyled-list campl-horizontal-navigation campl-global-navigation clearfix">
<li>
						<a href="#study-with-us">Study at Cambridge</a>
					</li>
					<li>
						<a href="#about-the-university">About the University</a>
					</li>
					<li>
						<a href="http://www.cam.ac.uk/research" class="campl-no-drawer">Research at Cambridge</a>
					</li>
				</ul>
</div>

			<div class="campl-column2">
				<div class="campl-quicklinks">
				</div>
			</div>

			<div class="campl-column2">

				<div class="campl-site-search" id="site-search-btn">

					<label for="header-search" class="hidden">Search site</label>
					<div class="campl-search-input">
						<form action="http://search.cam.ac.uk/web" method="get">
						<input id="header-search" type="text" name="query" value="" placeholder="Search"><input type="image" class="campl-search-submit " src="images/interface/btn-search-header.png">
</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="campl-row campl-global-header campl-search-drawer">
		<div class="campl-wrap clearfix">
			<form class="campl-site-search-form" id="site-search-container" action="">
				<div class="campl-search-form-wrapper clearfix">
					<input type="text" class="text" placeholder="Search"><input type="image" class="campl-search-submit" src="images/interface/btn-search.png">
</div>
			</form>
		</div>
	</div>

	<div class="campl-row campl-global-navigation-drawer">

		<div class="campl-wrap clearfix">
			<div class="campl-column12 campl-home-link-container">
				<a href="">Home</a>
			</div>
		</div>
		<div class="campl-wrap clearfix">
			<div class="campl-column12 campl-global-navigation-mobile-list campl-global-navigation-list">
				<div class="campl-global-navigation-outer clearfix" id="study-with-us">
					<ul class="campl-unstyled-list campl-global-navigation-header-container ">
<li><a href="http://www.cam.ac.uk/study-at-cambridge">Study at Cambridge</a></li>
					</ul>
<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list campl-global-navigation-secondary-with-children">
<li>
								<a href="http://www.study.cam.ac.uk/undergraduate/">Undergraduate</a>
								<ul class="campl-global-navigation-tertiary campl-unstyled-list">
<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/courses">Courses</a>
									</li>
									<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/applying">Applying</a>
									</li>
									<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/events">Events and open days</a>
									</li>
								  <li>
										<a href="http://www.undergraduate.study.cam.ac.uk/finance">Fees and finance</a>
									</li>
								  <li>
										<a href="http://www.becambridge.com/">Student blogs and videos</a>
									</li>
								</ul>
</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list campl-global-navigation-secondary-with-children">
<li>
								<a href="http://www.graduate.study.cam.ac.uk/">Graduate</a>
								<ul class="campl-global-navigation-tertiary campl-unstyled-list">
<li>
										<a href="http://www.graduate.study.cam.ac.uk/why-cambridge/welcome-vice-chancellor">Why Cambridge</a>
									</li>
									<li>
										<a href="http://www.graduate.study.cam.ac.uk/courses%0A">Course directory</a>
									</li>
									<li>
									<a href="http://www.graduate.study.cam.ac.uk/how-do-i-apply">How to apply</a>
</li>
									<li><a href="http://www.cambridgestudents.cam.ac.uk/fees-and-funding">Fees and funding</a></li>
									<li><a href="http://www.graduate.study.cam.ac.uk/faqs/applicant">Frequently asked questions</a></li>
								</ul>
</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list last">
<li>
								<a href="http://www.internationalstudents.cam.ac.uk">International students</a>
							</li>
							<li>
								<a href="http://www.ice.cam.ac.uk">Continuing education</a>
							</li>
							<li>
								<a href="http://www.epe.admin.cam.ac.uk/">Executive and professional education</a>
							</li>
							<li>
								<a href="http://www.educ.cam.ac.uk">Courses in education</a>
							</li>
						</ul>
</div>
				</div>

				<div class="campl-global-navigation-outer clearfix" id="about-the-university">
					<ul class="campl-global-navigation-header-container campl-unstyled-list">
<li><a href="http://www.cam.ac.uk/about-the-university">About the University</a></li>
					</ul>
<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.cam.ac.uk/about-the-university/how-the-university-and-colleges-work">How the University and Colleges work</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/history">History</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/visiting-the-university">Visiting the University</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/term-dates-and-calendars">Term dates and calendars</a>
							</li>
							<li class="last">
								<a href="http://map.cam.ac.uk">Map</a>
							</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.communications.cam.ac.uk/">For media</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/video-and-audio">Video and audio</a>
							</li>
							<li>
								<a href="http://webservices.admin.cam.ac.uk/fae/">Find an expert</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/publications">Publications</a>
							</li>
							<li class="last">
								<a href="http://www.cam.ac.uk/global-cambridge">Global Cambridge</a>
							</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.cam.ac.uk/news">News</a>
							</li>
							<li>
								<a href="http://www.admin.cam.ac.uk/whatson/">Events</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/public-engagement">Public engagement</a>
							</li>
							<li>
								<a href="http://www.jobs.cam.ac.uk">Jobs</a>
							</li>
							<li class="last">
								<a href="https://www.philanthropy.cam.ac.uk/">Give to Cambridge</a>
							</li>
						</ul>
</div>
				</div>

				<div class="campl-global-navigation-outer clearfix" id="our-research">
					<ul class="campl-global-navigation-header-container campl-unstyled-list">
<li><a href="">Research at Cambridge</a></li>
					</ul>
</div>
			</div>

			<ul class="campl-unstyled-list campl-quicklinks-list campl-global-navigation-container ">
<li>
					<a href="http://www.cam.ac.uk/for-staff">For staff</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/current-students">For current students</a>
				</li>
				<li>
					<a href="http://www.alumni.cam.ac.uk">For alumni</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/for-business">For business</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/colleges-and-departments">Colleges &amp; departments</a>
				</li>
				<li>
					<a href="http://www.lib.cam.ac.uk/libraries/">Libraries &amp; facilities</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/museums-and-collections">Museums &amp; collections</a>
				</li>
				<li class="last">
					<a href="http://www.cam.ac.uk/email-and-phone-search">Email &amp; phone search</a>
				</li>
			</ul>
</div>
	</div>
    <!-- .campl-global-header ends -->

	<div class="campl-row campl-page-header campl-sub-section-page">
		<div class="campl-wrap clearfix">
			<div class="campl-column12">
				<div class="campl-content-container">
					<div class="campl-breadcrumb" id="breadcrumb">
						<ul class="campl-unstyled-list campl-horizontal-navigation clearfix">
<li class="first-child">
								<a href="https://bioinfotraining.bio.cam.ac.uk/" class="campl-home ir">Home</a>
							</li>
							<li>
								<a href="">Courses</a>
							</li>
							<li>
								<a href="">Training Materials</a>
							</li>
							<li>
								<a href="index.html">Core Statistics in R
							</a>
</li>
						</ul>
</div>
					<!--<p class="campl-page-title">Bioinformatics Training Materials</p>-->

					<p class="campl-mobile-parent"><a href=""><span class="campl-back-btn campl-menu-indicator"></span>Studying at Cambridge</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="campl-row campl-page-header">
		<div class="campl-wrap clearfix campl-local-navigation" id="local-nav">
			<div class="campl-local-navigation-container">
				<ul class="campl-unstyled-list">
<li><a href="https://training.cam.ac.uk/bioinformatics/search">Course schedule</a></li>
					<li>
<a href="#" class="campl-selected">Additional information</a>
						<ul class="campl-unstyled-list local-dropdown-menu">
<li><a href="#">Additional resources</a></li>
							<li><a href="https://bioinfotraining.bio.cam.ac.uk/about/findus">Where to find us?</a></li>
							<li><a href="#">Frequently asked questions</a></li>
						</ul>
</li>
					<li><a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate">Further training</a></li>
				</ul>
</div>
		</div>



		<div class="campl-wrap clearfix campl-page-sub-title campl-recessed-sub-title">
			<div class="campl-column12">
				<div class="campl-content-container">
					<p class="campl-sub-title">Core Statistics in R</p>
				</div>
			</div>
		</div>
	</div>


		<div class="campl-row campl-content campl-recessed-content">
			<div class="campl-wrap clearfix">
				<div class="campl-column9  campl-main-content" id="content">
					<div class="campl-content-container">
						<div>
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <br><button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Overview</a></li>
<li class="book-part">CoreStats 1: Simple hypothesis testing</li>
<li><a class="" href="cs1-intro.html"><span class="header-section-number">2</span> Introduction</a></li>
<li class="book-part">CoreStats 1 (Practicals)</li>
<li><a class="" href="introduction.html"><span class="header-section-number">3</span> Introduction</a></li>
<li><a class="" href="cs1-one-sample-t-test.html"><span class="header-section-number">4</span> One-sample t-test</a></li>
<li><a class="" href="cs1-onesample-wilcoxon-signed-rank.html"><span class="header-section-number">5</span> Wilcoxon signed-rank test</a></li>
<li><a class="" href="cs1-students-t-test.html"><span class="header-section-number">6</span> Student’s t-test</a></li>
<li><a class="" href="cs1-mannwhitney-u-test.html"><span class="header-section-number">7</span> Mann-Whitney U test</a></li>
<li><a class="" href="cs1-paired-two-sample-t-test.html"><span class="header-section-number">8</span> Paired two-sample t-test</a></li>
<li><a class="" href="cs1-twosample-wilcoxon-signed-rank.html"><span class="header-section-number">9</span> Wilcoxon signed-rank test</a></li>
<li class="book-part">CoreStats 2: Categorical predictors</li>
<li><a class="" href="cs2-intro.html"><span class="header-section-number">10</span> Introduction</a></li>
<li class="book-part">CoreStats 2 (Practicals)</li>
<li><a class="" href="introduction-1.html"><span class="header-section-number">11</span> Introduction</a></li>
<li><a class="" href="cs2-anova.html"><span class="header-section-number">12</span> ANOVA</a></li>
<li><a class="" href="kruskal-wallis-test.html"><span class="header-section-number">13</span> Kruskal-Wallis test</a></li>
<li class="book-part">CoreStats 3: Continuous predictors</li>
<li><a class="" href="cs3-intro.html"><span class="header-section-number">14</span> Introduction</a></li>
<li class="book-part">CoreStats 3 (Practicals)</li>
<li><a class="" href="introduction-2.html"><span class="header-section-number">15</span> Introduction</a></li>
<li><a class="" href="correlation-coefficients.html"><span class="header-section-number">16</span> Correlation coefficients</a></li>
<li><a class="active" href="linear-regression.html"><span class="header-section-number">17</span> Linear regression</a></li>
<li class="book-part">CoreStats 4: Two predictor variables</li>
<li><a class="" href="cs4-intro.html"><span class="header-section-number">18</span> Introduction</a></li>
<li class="book-part">CoreStats 4 (Practicals)</li>
<li><a class="" href="introduction-3.html"><span class="header-section-number">19</span> Introduction</a></li>
<li><a class="" href="two-way-anova.html"><span class="header-section-number">20</span> Two-way ANOVA</a></li>
<li><a class="" href="linear-regression-with-grouped-data.html"><span class="header-section-number">21</span> Linear regression with grouped data</a></li>
<li class="book-part">CoreStats 5: Multiple predictor variables</li>
<li><a class="" href="cs5-intro.html"><span class="header-section-number">22</span> Introduction</a></li>
<li class="book-part">CoreStats 5 (Practicals)</li>
<li><a class="" href="introduction-4.html"><span class="header-section-number">23</span> Introduction</a></li>
<li><a class="" href="linear-models.html"><span class="header-section-number">24</span> Linear models</a></li>
<li><a class="" href="model-comparisons.html"><span class="header-section-number">25</span> Model comparisons</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="linear-regression" class="section level1" number="17">
<h1>
<span class="header-section-number">17</span> Linear regression<a class="anchor" aria-label="anchor" href="#linear-regression"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-6" class="section level2" number="17.1">
<h2>
<span class="header-section-number">17.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-6"><i class="fas fa-link"></i></a>
</h2>
<div class="objectives">
<p><strong>Questions</strong></p>
<ul>
<li>When should I use a linear regression?</li>
<li>How do I interpret the results?</li>
</ul>
<p><strong>Objectives</strong></p>
<ul>
<li>Be able to perform a linear regression in R</li>
<li>Use ANOVA to check if the slope of the regression differs from zero</li>
<li>Understand the underlying assumptions for linear regression analysis</li>
<li>Use diagnostic plots to check these assumptions</li>
</ul>
</div>
</div>
<div id="purpose-and-aim-5" class="section level2" number="17.2">
<h2>
<span class="header-section-number">17.2</span> Purpose and aim<a class="anchor" aria-label="anchor" href="#purpose-and-aim-5"><i class="fas fa-link"></i></a>
</h2>
<p>Regression analysis not only tests for an association between two or more variables, but also allows one to investigate quantitatively the nature of any relationship which is present, and thus determine whether one variable may be used to predict values of another.
Simple linear regression essentially models the dependence of a scalar dependent variable (y) on an independent (or explanatory) variable (x) according to the relationship:</p>
<p><span class="math display">\[\begin{equation*} 
y = \beta_0 + \beta_1 x
\end{equation*}\]</span></p>
<p>where <span class="math inline">\(\beta_0\)</span> is the value of the intercept and <span class="math inline">\(\beta_1\)</span> is the slope of the fitted line. The aim of simple linear regression analysis to assess whether the coefficient of the slope, <span class="math inline">\(\beta_1\)</span>, is actually different from zero. If it is different from zero then we can say that <span class="math inline">\(x\)</span> has a significant effect on <span class="math inline">\(y\)</span> (since changing <span class="math inline">\(x\)</span> leads to a predicted change in <span class="math inline">\(y\)</span>), whereas if it isn’t significantly different from zero, then we say that there isn’t sufficient evidence of a relationship. Of course, in order to assess whether the slope is significantly different from zero we first need to calculate the values of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
</div>
<div id="section-commands-9" class="section level2" number="17.3">
<h2>
<span class="header-section-number">17.3</span> Section commands<a class="anchor" aria-label="anchor" href="#section-commands-9"><i class="fas fa-link"></i></a>
</h2>
<p>No new commands used in this section.</p>
</div>
<div id="data-and-hypotheses-8" class="section level2" number="17.4">
<h2>
<span class="header-section-number">17.4</span> Data and hypotheses<a class="anchor" aria-label="anchor" href="#data-and-hypotheses-8"><i class="fas fa-link"></i></a>
</h2>
<p>We will perform a simple linear regression analysis on the two variables <code>murder</code> and <code>assault</code> from the <code>USArrests</code> dataset. We wish to determine whether the <code>assault</code> variable is a significant predictor of the <code>murder</code> variable. This means that we will need to find the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> that best fit the following macabre equation:</p>
<p><span class="math display">\[\begin{equation*}
Murder  = \beta_0 + \beta_1 \cdot Assault
\end{equation*}\]</span></p>
<p>And then will be testing the following null and alternative hypotheses:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <code>assault</code> is not a significant predictor of <code>murder</code>, <span class="math inline">\(\beta_1 = 0\)</span>
</li>
<li>
<span class="math inline">\(H_1\)</span>: <code>assault</code> is a significant predictor of <code>murder</code>, <span class="math inline">\(\beta_1 \neq 0\)</span>
</li>
</ul>
</div>
<div id="summarise-and-visualise-9" class="section level2" number="17.5">
<h2>
<span class="header-section-number">17.5</span> Summarise and visualise<a class="anchor" aria-label="anchor" href="#summarise-and-visualise-9"><i class="fas fa-link"></i></a>
</h2>
<p>You can visualise the data with:</p>
<div class="sourceCode" id="cb173"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create scatterplot of the data</span>
<span class="va">USArrests</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">assault</span>, y <span class="op">=</span> <span class="va">murder</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs3-practical-linear_regression_files/figure-html/unnamed-chunk-3-1.png" width="672"></div>
<p>There appears to be a relatively strong positive relationship between these two variables and whilst there is a reasonable scatter of the points around any trend line, we would probably expect a significant result in this case.</p>
</div>
<div id="assumptions-15" class="section level2" number="17.6">
<h2>
<span class="header-section-number">17.6</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-15"><i class="fas fa-link"></i></a>
</h2>
<p>In order for a linear regression analysis to be valid 4 key assumptions need to be met:</p>
<div class="highlight">
<ol style="list-style-type: decimal">
<li>The data must be linear (it is entirely possible to calculate a straight line through data that is not straight - it doesn’t mean that you should!)</li>
<li>The residuals must be normally distributed</li>
<li>The residuals must not be correlated with their fitted values</li>
<li>The fit should not depend overly much on a single point (no point should have high leverage).</li>
</ol>
</div>
<p>Whether these assumptions are met can easily be checked visually by producing four key diagnostic plots.</p>
<p>First we need to define the linear model:</p>
<div class="sourceCode" id="cb174"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lm_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">murder</span> <span class="op">~</span> <span class="va">assault</span>,
           data <span class="op">=</span> <span class="va">USArrests</span><span class="op">)</span></code></pre></div>
<ul>
<li>The first argument to <code>lm</code> is a formula saying that <code>murder</code> depends on <code>assaults</code>. As we have seen before, the syntax is generally <code>dependent variable</code> ~ <code>independent variable</code>.</li>
<li>The second argument specifies which dataset to use</li>
</ul>
<p>Next, we can create diagnostic plots for the model:</p>
<div class="sourceCode" id="cb175"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lm_1</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel</a></span><span class="op">(</span>plots <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"resid"</span>, <span class="st">"qq"</span>, <span class="st">"ls"</span>, <span class="st">"cookd"</span><span class="op">)</span>,
              smoother <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs3-practical-linear_regression_files/figure-html/cs3-lm-diagnostics-1.png" width="672"></div>
<ul>
<li>The top left graph plots the <strong>Residuals plot</strong>. If the data are best explained by a straight line then there should be a uniform distribution of points above and below the horizontal blue line (and if there are sufficient points then the red line, which is a smoother line, should be on top of the blue line). This plot is pretty good.</li>
<li>The top right graph shows the <strong>Q-Q plot</strong> which allows a visual inspection of normality. If the residuals are normally distributed, then the points should lie on the diagonal dotted line. This isn’t too bad but there is some slight snaking towards the upper end and there appears to be an outlier.</li>
<li>The bottom left <strong>Location-scale</strong> graph allows us to investigate whether there is any correlation between the residuals and the predicted values and whether the variance of the residuals changes significantly. If not, then the red line should be horizontal. If there is any correlation or change in variance then the red line will not be horizontal. This plot is fine.</li>
<li>The last graph shows the <strong>Cook’s distance</strong> and tests if any one point has an unnecessarily large effect on the fit. The important aspect here is to see if any points are larger than 0.5 (meaning you’d have to be careful) or 1.0 (meaning you’d definitely have to check if that point has an large effect on the model). If not, then no point has undue influence. This plot is good.</li>
</ul>
<div class="note">
<p>Formally, if there is any concern after looking at the diagnostic plots, then a linear regression is not valid. However, disappointingly, very few people ever check whether the linear regression assumptions have been met before quoting the results.</p>
<p>Let’s change this through leading by example!</p>
</div>
</div>
<div id="implement-test-9" class="section level2" number="17.7">
<h2>
<span class="header-section-number">17.7</span> Implement test<a class="anchor" aria-label="anchor" href="#implement-test-9"><i class="fas fa-link"></i></a>
</h2>
<p>We have already defined the linear model, so we can have a closer look at it:</p>
<div class="sourceCode" id="cb176"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># show the linear model</span>
<span class="va">lm_1</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = murder ~ assault, data = USArrests)
## 
## Coefficients:
## (Intercept)      assault  
##     0.63168      0.04191</code></pre>
<p>The function <code>lm</code> returns a linear model (lm) object which is essentially a list containing everything necessary to understand and analyse a linear model. However, if we just type the model name (as we have above) then it just prints to the screen the actual coefficients of the model i.e. the intercept and the slope of the line.</p>
<p>So here we have found that the line of best fit is given by:</p>
<p><span class="math display">\[\begin{equation*}
Murder = 0.63 + 0.042 \cdot Assault
\end{equation*}\]</span></p>
<p>Assess whether the slope is significantly different from zero:</p>
<div class="sourceCode" id="cb178"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm_1</span><span class="op">)</span></code></pre></div>
<p>Here, we again use the <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> command to assess significance. This shouldn’t be too surprising at this stage if the introductory lectures made any sense. From a mathematical perspective, one-way ANOVA and simple linear regression are exactly the same as each other and it makes sense that we should use the same command to analyse them in R.</p>
</div>
<div id="interpret-output-and-report-results-8" class="section level2" number="17.8">
<h2>
<span class="header-section-number">17.8</span> Interpret output and report results<a class="anchor" aria-label="anchor" href="#interpret-output-and-report-results-8"><i class="fas fa-link"></i></a>
</h2>
<pre><code>## Analysis of Variance Table
## 
## Response: murder
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## assault    1 597.70  597.70  86.454 2.596e-12 ***
## Residuals 48 331.85    6.91                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>This is exactly the same format as the table we saw for one-way ANOVA:</p>
<ul>
<li>The 1st line just tells you the that this is an ANOVA test</li>
<li>The 2nd line tells you what the response variable is (in this case <code>Murder</code>)</li>
<li>The 3rd, 4th and 5th lines are an ANOVA table which contain some useful values:
<ul>
<li>The <code>Df</code> column contains the degrees of freedom values on each row, 1 and 48 (which we’ll need for the reporting)</li>
<li>The <code>F</code> value column contains the F statistic, 86.454 (which again we’ll need for reporting).</li>
<li>The p-value is 2.596e-12 and is the number directly under the <code>Pr(&gt;F)</code> on the 4th line.</li>
<li>The other values in the table (in the <code>Sum Sq</code> and <code>Mean Sq</code>) column are used to calculate the F statistic itself and we don’t need to know these.</li>
</ul>
</li>
</ul>
<p>Again, the p-value is what we’re most interested in here and shows us the probability of getting data such as ours if the null hypothesis were actually true and the slope of the line were actually zero.
Since the p-value is excruciatingly tiny we can reject our null hypothesis and state that:</p>
<blockquote>
<p>A simple linear regression showed that the assault rate in US states was a significant predictor of the number of murders (F = 86.45, df = 1,48, p = 2.59x10<sup>-12</sup>).</p>
</blockquote>
<p><br></p>
<p><strong>Plotting the regression line</strong></p>
<p>It can be very helpful to plot the regression line with the original data to see how far the data are from the predicted linear values. We can do this with:</p>
<div class="sourceCode" id="cb180"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># plot the data</span>
<span class="va">USArrests</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">assault</span>, y <span class="op">=</span> <span class="va">murder</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs3-practical-linear_regression_files/figure-html/cs3-usarrests-abline-1.png" width="672"></div>
<ul>
<li>We plot all the data using <code><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point()</a></code>
</li>
<li>Next, we add the linear model using <code>geom_smooth(method = "lm")</code>, hiding the confidence intervals (<code>se = FALSE</code>)</li>
</ul>
</div>
<div id="exercise-3" class="section level2" number="17.9">
<h2>
<span class="header-section-number">17.9</span> Exercise<a class="anchor" aria-label="anchor" href="#exercise-3"><i class="fas fa-link"></i></a>
</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-12" class="exercise"><strong>Exercise 17.1  </strong></span>Linear regression</p>
<p>Calculate two simple linear regressions using the <code>data/tidy/CS3-statedata.csv</code> dataset, first for the variable <code>life_exp</code> on the variable <code>murder</code> and then for the variable <code>hs_grad</code> on <code>frost</code>.</p>
<p>Do the following in both cases:</p>
<ol style="list-style-type: decimal">
<li>Find the value of the slope and intercept coefficients for both regressions</li>
<li>Determine if the slope is significantly different from zero (i.e. is there a relationship between the two variables)</li>
<li>Produce a scatter plot of the data with the line of best fit superimposed on top.</li>
<li>Produce diagnostic plots and discuss with your (virtual) neighbour if you should have carried out a simple linear regression in each case</li>
</ol>
<details><summary>
Answer
</summary><p><strong>Murder and Life Expectancy</strong></p>
<p>Let’s see if the <code>murder</code> variable can be used to predict the <code>life_exp</code> variable. Let’s plot it first of all.</p>
<div class="sourceCode" id="cb181"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># plot the data and add the regression line</span>
<span class="va">USAstate</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">murder</span>, y <span class="op">=</span> <span class="va">life_exp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs3-practical-linear_regression_files/figure-html/unnamed-chunk-7-1.png" width="672"></div>
<p>We visualise for the same reasons:</p>
<ol style="list-style-type: decimal">
<li>We check that the data aren’t obviously wrong. Here we have sensible values for life expectancy (nothing massively large or small), and plausible values for murder rates (not that I’m that <em>au fait</em> with US murder rates in 1976 but small positive numbers seem plausible).</li>
<li>We check to see what we would expect from the statistical analysis. Here there does appear to be a reasonable downward trend to the data. I would be surprised if we didn’t get a significant result given the amount of data and the spread of the data about the line</li>
<li>We check the assumptions (only roughly though as we’ll be doing this properly in a minute). Nothing immediately gives me cause for concern; the data appear linear, the spread of the data around the line appears homogeneous and symmetrical. No outliers either.</li>
</ol>
<p>Now, let’s check the assumptions with the diagnostic plots.</p>
<div class="sourceCode" id="cb182"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a linear model</span>
<span class="va">lm_murder</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">life_exp</span> <span class="op">~</span> <span class="va">murder</span>,
           data <span class="op">=</span> <span class="va">USAstate</span><span class="op">)</span>

<span class="co"># create the diagnostic plots</span>
<span class="va">lm_murder</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel</a></span><span class="op">(</span>plots <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"resid"</span>, <span class="st">"qq"</span>, <span class="st">"ls"</span>, <span class="st">"cookd"</span><span class="op">)</span>,
              smoother <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs3-practical-linear_regression_files/figure-html/unnamed-chunk-8-1.png" width="672"></div>
<p>The Residuals plot appears symmetric enough (similar distribution of points above and below the horizontal blue line) for me to happy with linearity. Similarly the red line in the Location-Scale plot looks horizontal enough for me to be happy with homogeneity of variance. There aren’t any influential points in the Cook’s distance plot. The only plot that does give me a bit of concern is the Q-Q plot. Here we see clear evidence of snaking, although the degree of snaking isn’t actually that bad. This just means that we can be pretty certain that the distribution of residuals isn’t normal, but also that it isn’t <em>very</em> non-normal. What do we do in this situation? Well, there are three possible options:</p>
<ol style="list-style-type: decimal">
<li>Appeal to the <strong>Central Limit Theorem</strong>. This states that if we have a large enough sample size we don’t have to worry about whether the distribution of the residuals are normally distributed. <strong>Large enough</strong> is a bit of a moving target here and to be honest it depends on how non-normal the underlying data are. If the data are only a little bit non-normal then we can get away with using a smaller sample than if the data are massively skewed (for example). This is not an exact science, but anything over 30 data points is considered a lot for mild to moderate non-normality (as we have in this case). If the data were very skewed then we would be looking for more data points (50-100). So, for this example we can legitimately just carry on with our analysis without worrying.</li>
<li>Try transforming the data. Here we would try applying some mathematical functions to the response variable (<code>life_exp</code>) in the hope that repeating the analysis with this transformed variable would make things better. To be honest with you it might not work and we won’t know until we try. Dealing with transformed variables is legitimate as an approach but it can make interpreting the model a bit more challenging. In this particular example none of the traditional transformations (log, square-root, reciprocal) do anything to fix the slight lack of normality (you can take my word for it or you could try it using; <code>lm(log(LifeExp ~ Murder, data = USAstate))</code> for example.</li>
<li>Go with permutation methods / bootstrapping. This approach would definitely work. I don’t have time to explain it here (it’s the subject of an entire other practical). This approach also requires us to have a reasonably large sample size to work well as we have to assume that the distribution of the sample is a good approximation for the distribution of the entire dataset.</li>
</ol>
<p>So in this case, because we have a large enough sample size and our deviation from normality isn’t too bad, we can just crack on with the standard analysis.</p>
<p>So, let’s actually do the analysis:</p>
<div class="sourceCode" id="cb183"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm_murder</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: life_exp
##           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## murder     1 53.838  53.838  74.989 2.26e-11 ***
## Residuals 48 34.461   0.718                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>And after all of that we find that the murder rate is a statistically significant predictor of life expectancy in US states. Woohoo!</p>
<p><strong>High School Graduation and Frosty Days</strong></p>
<p>Now let’s investigate the relationship between the proportion of High School Graduates a state has (<code>hs_grad</code>) and the mean number of days below freezing (<code>frost</code>) within each state.</p>
<div class="sourceCode" id="cb185"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># plot the data</span>
<span class="va">USAstate</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">frost</span>, y <span class="op">=</span> <span class="va">hs_grad</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs3-practical-linear_regression_files/figure-html/unnamed-chunk-10-1.png" width="672"></div>
<p>Once again, we look at the data.</p>
<ol style="list-style-type: decimal">
<li>There doesn’t appear to be any ridiculous errors with the data; High School graduation proportions are in the 0-100% range and the mean number of sub-zero days for each state are between 0 and 365, so these numbers are plausible.</li>
<li>Whilst there is a trend upwards, which wouldn’t surprise me if it came back as being significant, I’m a bit concerned about…</li>
<li>The assumptions. I’m mainly concerned that the data aren’t very linear. There appears to be a noticeable pattern to the data with some sort of minimum around 50-60 Frost days. This means that it’s hard to assess the other assumptions.</li>
</ol>
<p>Let’s check these out properly</p>
<p>Now, let’s check the assumptions with the diagnostic plots.</p>
<div class="sourceCode" id="cb186"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a linear model</span>
<span class="va">lm_frost</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">hs_grad</span> <span class="op">~</span> <span class="va">frost</span>,
               data <span class="op">=</span> <span class="va">USAstate</span><span class="op">)</span>

<span class="co"># create the diagnostic plots</span>
<span class="va">lm_frost</span> <span class="op"><a href="https://rpkgs.datanovia.com/rstatix/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel</a></span><span class="op">(</span>plots <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"resid"</span>, <span class="st">"qq"</span>, <span class="st">"ls"</span>, <span class="st">"cookd"</span><span class="op">)</span>,
              smoother <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs3-practical-linear_regression_files/figure-html/unnamed-chunk-11-1.png" width="672"></div>
<p>We can see that what we suspected from before is backed up by the Residuals plot. The data aren’t linear and there appears to be some sort of odd down-up pattern here. Given the lack of linearity it just isn’t worth worrying about the other plots because our model is <strong>misspecified</strong>: a straight line just doesn’t represent our data at all.</p>
<p>Just for reference, and as practice for looking at diagnostic plots, if we ignore the lack of linearity then we can say that</p>
<ul>
<li>Normality is pretty good from the Q-Q plot</li>
<li>Homogeneity of variance isn’t very good and there appears to be a noticeable drop in variance as we go from left to right (from consideration of the Location-Scale plot)</li>
<li>There don’t appear to be any influential points (by looking at the Cook’s distance plot)</li>
</ul>
<p>However, none of that is relevant in this particular case since the data aren’t linear and a straight line would be the wrong model to fit.</p>
<p>So what do we do in this situation?</p>
<p>Well actually, this is a bit tricky as there aren’t any easy fixes here. There are two broad solutions for dealing with a misspecified model.</p>
<ol style="list-style-type: decimal">
<li>The most common solution is that we need more predictor variables in the model. Here we’re trying to explain/predict high school graduation only using the number of frost days. Obviously there are many more things that would affect the proportion of high school graduates than just how cold it is in a State (which is a weird potential predictor when you think about it) and so what we would need is a statistical approach that allows us to look at multiple predictor variables. We’ll cover that approach in the next two sessions.</li>
<li>The other potential solution is to say that high school graduation can in fact be predicted only by the number of frost days but that the relationship between them isn’t linear. We would then need to specify a relationship (a curve basically) and then try to fit the data to the new, non-linear, curve. This process is called, unsurprisingly, non-linear regression and we don’t cover that in this course. This process is best used when there is already a strong theoretical reason for a non-linear relationship between two variables (such as sigmoidal dose-response curves in pharmacology or exponential relationships in cell growth). In this case we don’t have any such preconceived notions and so it wouldn’t really be appropriate in this case.</li>
</ol>
<p>Neither of these solutions can be tackled with the knowledge that we have so far in the course but we can definitely say that based upon this data set, there isn’t a linear relationship (significant or otherwise) between frosty days and high school graduation rates.</p>
</details>
</div>
</div>
<div id="key-points-5" class="section level2" number="17.10">
<h2>
<span class="header-section-number">17.10</span> Key points<a class="anchor" aria-label="anchor" href="#key-points-5"><i class="fas fa-link"></i></a>
</h2>
<div class="keypoints">
<ul>
<li>Linear regression tests if a linear relationship exists between two or more variables</li>
<li>If so, we can use one variable to predict another</li>
<li>A linear model has an intercept and slope and we test if the slope differs from zero</li>
<li>We create linear models in R with the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> function and use <code><a href="https://rdrr.io/r/stats/anova.html">anova()</a></code> to assess the slope coefficient</li>
<li>We can only use a linear regression if these four assumptions are met:
<ol style="list-style-type: decimal">
<li>The data are linear</li>
<li>Residuals are normally distributed</li>
<li>Residuals are not correlated with their fitted values</li>
<li>No single point should have a large influence on the linear model</li>
</ol>
</li>
<li>We can use <code><a href="https://goodekat.github.io/ggResidpanel/reference/resid_panel.html">resid_panel()</a></code> to get diagnostic plots in R, which help evaluate these assumptions</li>
</ul>
</div>

</div>
</div>



  <div class="chapter-nav">
<div class="prev"><a href="correlation-coefficients.html"><span class="header-section-number">16</span> Correlation coefficients</a></div>
<div class="next"><a href="cs4-intro.html"><span class="header-section-number">18</span> Introduction</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#linear-regression"><span class="header-section-number">17</span> Linear regression</a></li>
<li><a class="nav-link" href="#objectives-6"><span class="header-section-number">17.1</span> Objectives</a></li>
<li><a class="nav-link" href="#purpose-and-aim-5"><span class="header-section-number">17.2</span> Purpose and aim</a></li>
<li><a class="nav-link" href="#section-commands-9"><span class="header-section-number">17.3</span> Section commands</a></li>
<li><a class="nav-link" href="#data-and-hypotheses-8"><span class="header-section-number">17.4</span> Data and hypotheses</a></li>
<li><a class="nav-link" href="#summarise-and-visualise-9"><span class="header-section-number">17.5</span> Summarise and visualise</a></li>
<li><a class="nav-link" href="#assumptions-15"><span class="header-section-number">17.6</span> Assumptions</a></li>
<li><a class="nav-link" href="#implement-test-9"><span class="header-section-number">17.7</span> Implement test</a></li>
<li><a class="nav-link" href="#interpret-output-and-report-results-8"><span class="header-section-number">17.8</span> Interpret output and report results</a></li>
<li><a class="nav-link" href="#exercise-3"><span class="header-section-number">17.9</span> Exercise</a></li>
<li><a class="nav-link" href="#key-points-5"><span class="header-section-number">17.10</span> Key points</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

					</div>
				</div>
				<!-- Related links -->
				<!--<div class="campl-column3 campl-secondary-content">
					<div class="campl-content-container">
						<div class="campl-heading-container">
							<h2>Related Links</h2>
						</div>
						<ul class='campl-unstyled-list campl-related-links'>
							<li><a href="#">Lorem ipsum dolor sit amet</a></li>
							<li><a href="#">Consectetur adipisicing elit</a></li>
							<li><a href="#">Sed do eiusmod tempor incididunt extra long wrapping on to two line</a></li>
							<li><a href="#">Labore et dolore magna aliqua</a></li>
							<li><a href="#">Ut enim ad minim veniam</a></li>
							<li><a href="#">Quis nostrud exercitation ullamco</a></li>
						</ul>
					</div>
					<div class="campl-content-container">
						<div class="campl-vertical-teaser campl-teaser campl-promo-teaser">
							<div class="campl-content-container campl-vertical-teaser-txt">
								<p class='campl-teaser-title'><a href="#">Promo teaser with title above</a></p>
							</div>
							<div class="campl-content-container campl-vertical-teaser-img">
								<a href="#" class="campl-teaser-img-link"><img alt=""  src="images/content/homepage-promo-placeholder.png" class="campl-scale-with-grid" /></a>
							</div>
							<div class="campl-content-container campl-vertical-teaser-txt clearfix">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
								<a href="#4" class="campl-secondary-cta campl-float-right">Read more</a>
							</div>
						</div>
					</div>
				</div>-->
			</div>
		</div>
		<div class="campl-row campl-local-footer">
			<div class="campl-wrap clearfix">
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Contact us</h3>
						 <div class="content">
						   <p>Bioinformatics Training Department of Genetics University of Cambridge Downing Street Cambridge CB2 3EH United Kingdom</p>
						   <h3>Contact:</h3> <a href="mailto:%20bioinfotraining@bio.cam.ac.uk">bioinfotraining@bio.cam.ac.uk</a>
						 </div>
					</div>
				</div>
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Bioinformatics Training</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/undergraduate">Undergraduate training</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate">Postgraduate training</a>
							</li>
						</ul>
</div>
				</div>
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Postgraduate Courses by Theme</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/programming">Basic Skills and Programming</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/services">Databases and Services</a>
							</li>
							<li>
							  <a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/specialized">Specialised Topics</a>
							</li>
						</ul>
</div>
				</div>
				<div class="campl-column3 campl-footer-navigation last">
					<div class="campl-content-container campl-navigation-list">
						<h3>About Bioinformatics Training</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about">About the Facility</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about/findus">How to find us</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about/visitors">Visiting Cambridge</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/privacy-and-cookie-policies">Privacy and Cookies policy</a>
							</li>
						</ul>
</div>
				</div>
			</div>
		</div>
	<div class="campl-row campl-global-footer">
		<div class="campl-wrap clearfix">
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-footer-logo">
					<img alt="University of Cambridge" src="images/interface/main-logo-small.png" height="38px;" class="campl-scale-with-grid"><p>© 2021 University of Cambridge</p>
						<ul class="campl-unstyled-list campl-global-footer-links">
<li>
								<a href="http://www.cam.ac.uk/university-a-z">University A-Z</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/contact-the-university">Contact the University</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-this-site/accessibility">Accessibility</a>
							</li>
							<li>
								<a href="http://www.admin.cam.ac.uk/univ/information/foi/">Freedom of information</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-this-site/terms-and-conditions">Terms and conditions</a>
							</li>
						</ul>
</div>
			</div>
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-navigation-list">

					<div class="link-list">
						<h3><a href="http://www.cam.ac.uk/study-at-cambridge">Study at Cambridge</a></h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="http://www.study.cam.ac.uk/undergraduate/">Undergraduate</a>
							</li>
							<li>
								<a href="http://www.graduate.study.cam.ac.uk/">Graduate</a>
							</li>
							<li>
								<a href="http://www.internationalstudents.cam.ac.uk">International students</a>
							</li>
							<li>
								<a href="http://www.ice.cam.ac.uk">Continuing education</a>
							</li>
							<li>
								<a href="http://www.epe.admin.cam.ac.uk/">Executive and professional education</a>
							</li>
							<li>
								<a href="http://www.educ.cam.ac.uk">Courses in education</a>
							</li>
						</ul>
</div>
				</div>
			</div>
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-navigation-list">
					<h3><a href="http://www.cam.ac.uk/about-the-university">About the University</a></h3>
					<ul class="campl-unstyled-list campl-page-children">
<li>
							<a href="http://www.cam.ac.uk/about-the-university/how-the-university-and-colleges-work">How the University and Colleges work</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/about-the-university/visiting-the-university">Visiting the University</a>
						</li>
						<li>
							<a href="http://map.cam.ac.uk">Map</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/news">News</a>
						</li>
						<li>
							<a href="http://www.admin.cam.ac.uk/whatson/">Events</a>
						</li>
						<li>
							<a href="http://www.jobs.cam.ac.uk">Jobs</a>
						</li>
						<li>
							<a href="https://www.philanthropy.cam.ac.uk/">Give to Cambridge</a>
						</li>
					</ul>
</div>
			</div>
			<div class="campl-column3 campl-footer-navigation last">
				<div class="campl-content-container campl-navigation-list">
					<h3><a href="http://www.cam.ac.uk/research">Research at Cambridge</a></h3>
					<ul class="campl-unstyled-list">
<li>
							<a href="http://www.cam.ac.uk/research/news">News</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/features">Features</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/discussion">Discussion</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/spotlight-on">Spotlight on...</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/research-at-cambridge">About research at Cambridge</a>
						</li>
					</ul>
</div>
			</div>
		</div>
	</div>
	<!-- .campl-global-footer ends -->

<!--[if lte IE 8]>
</div>
<![endif]-->

	<script type="text/javascript" src="javascripts/libs/ios-orientationchange-fix.js"></script><script type="text/javascript" src="javascripts/libs/jquery-min.js"></script><script type="text/javascript" src="javascripts/libs/modernizr.js"></script><script type="text/javascript" src="javascripts/custom.js"></script><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
